input-output-hk/cardano-ledger-specs

docs/delegation_design_spec/delegation_design_spec.tex
Deleted the empty assumptions section. Fixed all \hyperref references into \cref cross references. Fixed a bunch of spelling errors, and various minor grammatical improvements.
=> Minor edits to the delegation doc, cross references, spelling, grammar

latex/delegation.tex, latex/ledger-spec.tex, latex/references.bib
This PR adds certificate deposits and refunds to the latex spec.  It also adds a transaction time-to-live, which was needed for refunds.
The UTxO ledger rules are now less separated from delegation. This is due to the fact that the preservation of value condition now takes certificate refunds into account.  The caused a few things to be reordered.  Delegation is now defined first, and some of the abstract types are grouped differently.
closes #25
=> adding deposits, refunds, and time-to-live

.travis.yml
This activates a Travis CI run only if the feature branch has a prefix "haskell", e.g., `haskell/feature1` would build, `latex/feature1` wouldn't. The reasoning is that we only really want Travis to run on code changes. The implementation has potential to be optimized though ...
closes #43
=> Conditional Travis Run

latex/ledger-spec.tex
UTxO transactions have inherent replay protection, since the transaction inputs are unique and can only be spent once.  Other features of transactions, such as delegation certificates, do not have such inherit protection.  Such feature can piggyback off the UTxO replay protection, however, if we require that the signatures for these features include the transaction body and contain at least one transaction input.  This does exclude, however, the possibility of being able to do things like paying for something entirely with delegation certificate refunds.
This PR adds a predicate to the UTxO antecedent, requiring at least one input.
closes #52
=> prevent replay attacks by requiring nonempty txins

hs/test/Tests.hs
This adds properties 7.2 - 7.5. 7.1 needs rewards and deposits which currently aren't part of the executable model.
=> Add Properties of transaction state transitions as Tests in executable model

latex/delegation.tex, latex/iohk.sty, latex/ledger-spec.tex
The map `stpools` which has type `HashKey -> (StakePool, Slot)` makes the notation confusing and awkward in several places in the latex spec.  This PR separates it into two maps and cleans up the notation.
additionally, the PR splits the `DELEGW` rule into two rules, so that now it conforms to the small step semantics.
closes #58  closes #64
=> splitting stpools into two maps [skip ci]

hs/package.yaml, hs/stack.yaml, hs/test/Tests.hs
Use coverage classification to get more insight into the generated tests in terms of executed transactions and final coin distribution.
=> First property-based test with coverage classification

docs/accounting/Accounting.lhs, docs/accounting/Makefile, docs/accounting/accounting/test/Test.hs
The stand-alone accounting document has been updated so that pools are only refunded on epoch boundaries.  As such, pool retirements are now tracked by the ledger state.
=> refund pools only at epoch

latex/delegation.tex, latex/epoch.tex, latex/iohk.sty, latex/ledger-spec.tex
This PR introduces a new section for the rules needed for transitioning from one epoch to the next.
The main rule, `EPOCH`, combines four rules together: `UTXOEP`, `ACCNT`, `POOLCLEAN`, and `NEWPC`.
The `UTXOEP` rule is responsible for processing the reward withdrawals (moving them from a pending state to spendable UTxO), zeroing out the fee pool, and setting the deposit pool to the minimum needed.
The `ACCNT` rule handles moving value between the treasury, reserves, reward pool, and the current reward accounts.  Note that the actual reward function, based on the actual blocks produced during the epoch, is left unspecified.  There are still some details there to be worked out by the researchers.
The `POOLCLEAN` rule pays out pool retirement certificate refunds and retires pools.
The …
=> epoch rules

hs/src/LedgerState.hs, hs/src/UTxO.hs, hs/test/Generator.hs, hs/test/Mutator.hs, hs/test/Tests.hs
In this PR the `LedgerEntry` type is removed, so that a ledger is just a list of transactions, and the transactions contain delegation certificates.
=> using delegation certs inside transaction

hs/src/LedgerState.hs, hs/test/Tests.hs
In order to prevent a replay attack, i.e., applying a delegation transaction again later, it is necessary to consume an input.
This adds the above validation, a unit test for it and fixes a unit test that did apply a transaction with empty input set.
=> Add validation of non-empty input sets for transactions

hs/package.yaml, hs/test/Generator.hs, hs/test/Tests.hs
This adds the possibility to collect all transactions and check that the multiset union of all inputs does not contain any duplicates.
This property itself depends on the way that the transactions are generated of course, therefore there is also a mutation variant that mutates transactions and classifies into validated and non-validated double-spends. Only non-validated double-spends are OK, else the property fails.
=> Add property and classification to check absence of double spend

hs/src/Coin.hs, hs/src/Delegation/Certificates.hs, hs/src/LedgerState.hs, hs/src/PrtlConsts.hs, hs/src/Slot.hs, hs/src/UTxO.hs, hs/test/Generator.hs, hs/test/Mutator.hs, hs/test/Tests.hs
This PR add support for deposits and refunds.  In order to do this, transaction time-to-live was also added.
Some other small notes:
- the stake pool map in the ledger state is now split into two maps (match the spec).
- The epoch was removed from the ledger state (this lives in the environment, not the state).
- I changed the `minfee` calculation to be based on the "bytes" of the transaction body (instead of the full transaction with witnesses).
- I tried to clean up some of the boilerplate involved in the unit tests, by making a generic method for when `Alice` wants to send coin to `Bob`.
closes #86
=> adding deposits and refunds

latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex
The Addr type is now (base U pointer U reward).
In the (addr_h utxo pointeraddr) calculation, we have
{ a \mapsto h | i \mapsto (a,_) \in utxo /\ a \mapsto h \in pointeraddr}
Which means any address in the transaction has to be a pointer address, and pointer addresses are only for registered staking keys, 
not arbitrary paying keys. How should this work?
=> Pointer addresses

latex/shell.nix
`nix-shell --pure --run make` was failing for me on `master`. This is the change that I needed to get it working.
=> Get nix-shell working for gitinfo2

hs/src/Delegation/Certificates.hs, hs/src/EpochBoundary.hs, hs/src/LedgerState.hs, hs/src/PrtclConsts.hs, hs/src/UTxO.hs, hs/test/Generator.hs, hs/test/UnitTests.hs, latex/epoch.tex
implement functions used in reward calculation, i.e., `maxPool`, `movingAvg` and `poolRew`
depends on #163
=> Implement functions for epoch boundary

hs/src/EpochBoundary.hs, hs/src/LedgerState.hs, hs/src/PParams.hs, hs/test/Generator.hs, hs/test/UnitTests.hs, latex/epoch.tex
some small changes / adaption in the latex doc for typing
more involved change: transform set of `TxOut` to `[TxOut]` to make sure no elements can get lost in `stake` calculation.
=> Implement STS rules for epoch boundary

latex/delegation.tex, latex/ledger-spec.tex
This PR creates a singe table to consolidate all the definitions relating to addresses.  This includes reward accounts and the three output addresses: base, ptr, and enterprise.  Enterprise addresses are new.  They do nothing but exist for payments and are excluded for staking.
This will be a general pattern that we will follow for a couple up-coming topics. We will be consolidating protocol constants and transaction definitions as well.  This means that some definitions will be introduced before they are strictly needed.  It should, however, add to the readability and coherence.
I have not attempted to move the prose to the correct section. I will do this after all the regrouping is finished.
#174
=> consolidate all address definitions into one table

latex/epoch.tex
This PR prevents the `NEWPC` transition from blocking the entire system in the situation where the reserve pot is insufficient to account for the difference in refund obligations demanded by a protocol update.  Instead of blocking, the new now simple ignores the update.
Additionally, the environment for this transition system was corrected in the transition rule.
#195
=> NEWPC transition is a no-op when costs are not met

latex/delegation.tex, latex/epoch.tex
This PR combines the `UTxOEP` and `ACCNT` transition systems. The accounting state now includes `utxoSt`, which is manipulated by setting the deposit pot to the current obligations and the fee pot to zero.
This PR also makes several cosmetic changes:
- the variable name `pc` is no longer a good choice for what is now called the `PParams` type (protocol parameters). These have been replaced with `pp`.
- The above change means that `pparams` is now a bad choice of names for the pool parameters variables. So these have been changed to `poolParams`.
- The prococol parameters tau and rho are now explicitly accessed via the `globalAccntng` accessor.
- Two of the other accessor methods were renamed, `poolConsts` is now `globalPool` and `poolSpec` is now `poolCosts`.
- `rewardPool` is now called …
=> combine the UTxOEP and ACCNT transtions

latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex
The `Allocs` type has, up until now, been representing both the registered stake keys and the registered stake pools. It is an alias for `HashKey |-> Slot`, since we keep track of the slot when registrations happened in order to calculate the deposit refunds.
We realized, however, that this generality (ie have one type for both) was both never really needed and confusing. Therefore this PR removes `Allocs` and replaces it with `StakeKeys` and `StakePools`. The aliases are the same as they were before: `HashKey |-> Slot`.
This forced a bit of other renaming.  The previous type which held the stake pool parameters has been changed from `StakePool` to `PoolParam`.  We now use the variable name `poolParam` to represent the parameters associated with a single stake pool, and `poolParams` …
=> Allocs type split into StakeKeys and StakePools

latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex
This is a rather large PR that cleans up the reward calculation.  A couple fundamental issues were resolved, namely 1) adding support for pool owners, and 2) giving unrealized rewards to the treasury.
The functions involved in the reward calculation are all very connected, and for this reason I resolved a lot of issues at once.  I wanted to make changes more incrementally, but I could not find a good way to do so.
The most relevant changes happened in (what are now numbered as) Figures:
- 25 - helper functions for the stake distribution
- 26 - stake distribution
- 27 - the reward functions from the delegation design doc
- 28 - the reward splitting from the delegation design doc
- 29 - the plumbing that glues all the reward calculations together
- 33 the accounting transition was changed a …
=> Reworking the reward calculation

latex/ledger-spec.tex, latex/properties.tex
This adds some first properties for the reward calculation functions.
For the actual reward, the property cannot be calculated per stake pool, but only for all pools together, as the maximal reward is an expected maximal reward and cannot be guaranteed to be bounded by `maxP`
=> Properties on the calculation functions

latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex, latex/properties.tex
In the many changes to the spec recently, the prose became further out of sync with the tables.  This PR is a large overhaul of the prose which mostly lines things back up again.
Additionally, there is a much heavier use bullet point lists, as per #193.  The lists should make comparing the prose with the tables much easier, since they correspond very closely now.
Over the past several previous PRs, helper functions have been separated and labeled as such. This is completed now, see #182 
The `POOLCLEAN` rule needed a bit of redoing, so I took the opportunity to rename it `POOLREAP` and have it remove delegations to retiring pools, as in #179.  The transition needed redoing since it was missing pool cert refunds, which are now added.  It was decided that these refunds will go to the reward …
=> reordering prose and adding pool refunds

.gitignore, latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex, latex/non-integral.tex, latex/properties.tex
This PR adds stake distribution snapshots to the reward calculation.  The main change was to split up the `ACCNT` transition into two parts: 1) the part that calculates the stake distribution, and 2) the part that hands out the rewards.
There is now an overview subsection with:
Note the "mark, set, go" mnemonic. I thought that using numbers to index the snapshots would get too confusing.
The epoch boundary rule now uses a new `SNAPS` transition system in place of `ACNT`.
Note that the decayed deposits are now transferred to the fee pot at the epoch boundary, and not during the total pot calculation. The fee and the decayed amount are also snapshotted into a single value during `SNAP`, since the reward calculation will happen mid-epoch.
The other half of the old `ACNT`, namely the reward …
=> Stake distribution snapshots

latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex
This PR redoes the translations between epochs and slots.  #180 
The number of slots in an epoch is now defined as a global constant (in table 4, along with the protocol parameters).
It is now explicit that the decayed deposit amounts that are moved to the rewards pot at the epoch boundary are always calculated based on the first slot of the upcoming epoch.
In fact, in the epoch boundary transition (Fig 34), and also all three transitions that it depends on it (Figs 29, 31, and 33), the slot in the environment has been replaced with `e_new`, hopefully making it clear that the calculations are done based on the upcoming epoch number. Moreover, when a slot number is needed in these transitions, `firstSlot e_new` is always used.
There were also a couple cosmetic changes. I've switched the …
=> Redo epochs and slots

dependencies/non-integer/src/NonIntegral.hs, dependencies/non-integer/test/Spec.hs, hs/src/LedgerState.hs
This cleans up the warnings and adds some documentation to the `non-integer` library.
=> Cleanup warnings / add documentation to `non-integer`

latex/delegation.tex, latex/epoch.tex, latex/intro.tex, latex/ledger-spec.tex, latex/properties.tex
- calculate epochs and slots explicitly using `SlotsPerEpoch`
- remove rogue space from using `\cwitness{}` in text.
- make withdrawal reward balance a separate function (so now there is `ubalance` and `wbalance`).
- subscript the hashkeys in fig 3 with `pay` and `stake`
- allow zero-valued coins
- shorten sums in the `deposits` function in figure 9 with intersections
=> cosmetic changes from pre-version-1.2 review pt 1

specs/chain/hs/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, specs/chain/hs/test/Cardano/Spec/Chain/STS/Properties.hs, specs/ledger/hs/src/Ledger/Core.hs, specs/ledger/hs/src/Ledger/Delegation.hs, specs/ledger/hs/test/Ledger/Delegation/Examples.hs, specs/ledger/hs/test/Ledger/Delegation/Properties.hs, specs/semantics/hs/src/Control/State/Transition/Trace.hs, specs/semantics/hs/src/Data/AbstractSize.hs
- Add doctests for `Control.State.Transition.Trace`.
- Replace `Natural` by `Word64` for abstractslots and epochs, otherwise we are making things difficult to ourselves when elaborating this into concrete slots and epochs, since they have type `Word64`
- Correct the meaning of `OldestFirst` and `NewestFirst` which was swapped.
- Add (`lens`) getters for parts of the chain state.
- Add function `preStatesAndSignals` to pair a signal with its pre-state.
Closes #248.
=> Bring the required changes for pr308 to this repo

latex/delegation.tex, latex/epoch.tex, latex/notation.tex, latex/utxo.tex
This PR presents the stake distribution calculation in a different way, by using relations:
Additionally, I've removed the `PooledStake` type, and no longer pass around that nested structure (which consolidated the pool owners into a single key value pair).  Now instead we pass along the (un-pooled) stake distribution together with the delegation map. Such as in the stake distribution snapshots:
When we do need to filter down to one pool, we use this new method:
Besides that, there were just a few minor edits:
1) there was still a reference to the `ACNT` rule, which is now called `REWARD`
2) there was a paragraph about how withdrawal accounts work that was describing how things _used_ to work, so it was removed
3) a clarification in the prose where "delegation certificate" was vague (ie …
=> calculating stake distribution with relations

latex/combined-spec.tex, latex/default.nix
The combined ledger spec was not building. It was still using git revisions, and the nix script was missing tikz-cd.
I've made #269 so that we can keep things in sync.
=> combined spec now builds again

specs/chain/hs/cs-blockchain.cabal, specs/chain/hs/src/Cardano/Spec/Chain/STS/Block.hs, specs/chain/hs/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, specs/chain/hs/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, specs/chain/hs/src/Cardano/Spec/Consensus/Block.hs
This patch both updates block-related types and provides a few new classes for interfacing with the consensus layer.
Closes #238.
=> Updates the block-related types in the Byron era chain spec

.travis.yml, specs/chain/hs/test/Cardano/Spec/Chain/STS/Properties.hs
Before we ran Travis only on branches with `haskell` prefix, this prevented the compilation error to be caught. This also removes this behavior.
=> Fix compilation error on Travis CI

dependencies/non-integer/app/Main.hs, dependencies/non-integer/reference/non_integral.c, dependencies/non-integer/reference/non_integral_test.cpp, dependencies/non-integer/reference/randomize.cpp, dependencies/non-integer/src/NonIntegral.hs
succeeds with `x^y` on 
- 10.000.000 pairs from [0.1, 4.1]
- 1.000.000 between [0.1;19.1]
UPDATE:
- 20.000.000 pairs from `[0.1; 100.1]`
with 34 decimal digits of precision
to reproduce, compile `randomize.cpp` with `-lgmpxx -lgmp` and run it with the number of desired pairs as input on stdin
`non_integral_test.cpp` and `app/Main.hs` both read linewise from stdin and compute `x^y` as output per line
=> Converging reference and Haskell implementation

.stack-to-nix.cache, nix/.stack-pkgs.nix, nix/.stack.nix/cardano-crypto.nix, nix/.stack.nix/cs-ledger.nix, nix/.stack.nix/delegation.nix, nix/.stack.nix/hedgehog.nix, nix/.stack.nix/non-integer.nix, specs/chain/hs/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, specs/ledger/hs/src/Ledger/Core.hs, specs/ledger/hs/src/Ledger/UTxO.hs, specs/ledger/hs/src/Ledger/Update.hs, specs/ledger/latex/blockchain-interface.tex, stack.yaml
This commit also introduces the `Maplike` class which provides some
functionality to write things abstracted over `Map a b` and `Set (a,b)`, albeit
the latter must be wrapped in a newtype.
=> Add: Update interface

docs/delegation_design_spec/CHANGELOG.md, docs/delegation_design_spec/delegation_design_spec.tex, docs/delegation_design_spec/references.bib
Further updates to the design document, following Berlin and more recent discussions.
=> Delegation design Update

latex/CHANGELOG.md, latex/chain.tex, latex/epoch.tex, latex/ledger-spec.tex, latex/ledger.tex, latex/notation.tex, latex/protocol-parameters.tex, latex/references.bib
This is a first attempt at a blockchain layer transition system for the Shelley ledger spec, corresponding to Praos.  It's a work in progress, but I don't want the next PR to be too huge (it's already quite large).
There is no prose yet, just tables.
A new section was added, `11 Blockchain layer`.  There are four new transition systems: `BHEAD`, `NEWEPOCH`, `BBODY`, and `CHAIN`.  The `CHAIN` transition is now the topmost transition from which all the others are called.  Most of Praos shows up in `BHEAD` and the `VRF` subsection 11.1.
The rest of the document was largely untouched.  I just needed to have a rule which iterated the `LEDGER` rule on a list of transaction, and I needed to add two new protocol parameters (`stableAfter`, aka `k`, and `activeSlotCoeff`, aka `f`).
=> Added a blockchain layer to the spec for praos

latex/delegation.tex, latex/epoch.tex, latex/ledger.tex, latex/notation.tex, latex/utxo.tex
Use `:=` notation throughout the Shelley ledger spec for let bindings.  #313
=> using := for let binding symbol

docs/delegation_design_spec/Makefile, specs/chain/hs/default.nix, specs/chain/hs/shell.nix, specs/ledger/hs/default.nix, specs/ledger/hs/shell.nix, specs/semantics/hs/default.nix, specs/semantics/hs/shell.nix
- Delegation design spec now builds correctly.
- Fix up the individual nix files in various haskell subdirs.
- Remove the corresponding shell.nix files in those subdirs. I could have fixed
them, but I'm unconvinced anyone is using them, so I'd rather have less to
bitrot. We can add them back if needed/wanted.
Addresses #304
=> Fix: Various features of the nix build.

specs/chain/hs/src/Cardano/Spec/Consensus/Block.hs
As discussed in the issue #276, to be able to use the STS rules for `cs-blockchain` (the Byron era chain), this PR provides a function that converts a polymorphic block into the concrete block type used by the top-level STS for the chain.
Closes #276.
=> Issue #276: Allows for using chain STS rules with a polymorphic block

latex/chain.tex, latex/crypto-primitives.tex, latex/epoch.tex, latex/intro.tex, latex/references.bib
This PR updates the reward calculation section to be compatible with the new chain level transitions.  Instead of calculating the reward information and immediately applying it to the epoch state, we need to calculate the relevant information and save it as an update which can be applied later.
In particular:
The `REWARD` transition has been replaced by a function `createRUp`.  It does nearly the same thing as `REWARD`, but instead of modifying the epoch state, it creates an `RewardUpdate`:
The updates can then be applied to the epoch state with the new `applyRUpd` function. I've used notation reminiscent of the transition systems for this function since I think it reads nicely:
Some other smaller changes were made as well:
The `EPOCH` transition, and the three transitions that it calls, …
=> chain level reward updates in Shelley ledger spec

latex/chain.tex, latex/crypto-primitives.tex, latex/delegation.tex, latex/epoch.tex, latex/ledger-spec.tex, latex/ledger.tex, latex/non-integral.tex, latex/protocol-parameters.tex, latex/references.bib
This PR introduces operational certificates to the Shelley ledger spec, as described in section `4.4.7` of the delegation design document. #338 
The block header now includes an additional item, the `OCert`, defined as:
The hot keys used in the operational certs use key evolving signatures, and require an additional table in the cryptography section.  Essentially, pubkeys are fixed as before, but private keys can be evolved, with the new constraint that when you verify a signature, the verifier verifies against a minimal number of evolutions that must have occurred:
The previous rule `BHEAD` has been modified so that instead of checking that the pool operator key (ie cold key) signed the header, we now check that the (hot) operational key signed the header, given the proper number of …
=> operational certificates in shelley ledger spec

.gitignore, README.md, dependencies/non-integer/doc/default.nix, docs/delegation_design_spec/default.nix, latex/default.nix, nix/fetch-nixpkgs.nix, nix/nixpkgs-src.json, specs/chain/latex/default.nix, specs/ledger/latex/default.nix, specs/semantics/latex/default.nix
This seems to be the right way of pinning the version of the `nix` packages
used by IOHK.
`nix/fetch-nixpkgs.nix` and `nix/nixpkgs-src.json` were also removed since they
don't seem to be necessary anymore.
=> Use `lib.nix` instead of `nix/fetch-nixpkgs.nix`.

.gitignore, README.md, dependencies/non-integer/doc/references.bib, dependencies/non-integer/non-integer.cabal, hs/delegation.cabal
Also change `fm-ledger-rules` to `cardano-ledger-specs` in:
- dependencies/non-integer/doc/references.bib
- dependencies/non-integer/non-integer.cabal
- hs/delegation.cabal
=> Update the links to the PDF documents compiled in our hydra server

latex/CHANGELOG.md, latex/chain.tex, latex/crypto-primitives.tex, latex/epoch.tex, latex/protocol-parameters.tex
- `activeCoeffSlot` is now a protocol parameter
- the KES evolution number is now the same for signer and verifier
- added context for the divisions of the epoch
- updated the changelog
- closed all the questions except for the one about wall-clock
closes #351 #355 #356
=> Small edits to the chain-level validation

specs/ledger/latex/blockchain-interface.tex, specs/ledger/latex/update-mechanism.tex
On epoch change, now we discard the the pending protocol update proposals:
The `PVBUMP` transition system is now in its own Figure:
We need not clean up the `fads` set anymore, since it will get cleaned up on protocol parameters change.
The `UPPVV` (update protocol version validation) rule registers the update as the current protocol parameters overwritten by the values in the update proposal. This allows for a simpler implementation (since we do not have to consider `Maybe` values):
The `canUpdate` function is simplified now by using the protocols parameters map as a function:
Closes #357
=> Discard pending update proposals on protocol parameters change

.gitignore, byron/ledger/formal-spec/Makefile, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/notation.tex, byron/ledger/formal-spec/update-mechanism.tex
- Adapt the update rules so that the meaning of `upAdptThd` coincides with `srMinThd . ppSoftforkRule` in the implementation.
- Remove unused current epoch from the environment of the update interface rules.
- Use synctex in the ledger specs.
Closes #377 
Closes #296
=> Adapt the meaning of `upAdpThd` to coincide with the actual implementation

shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/intro.tex, shelley/chain-and-ledger/formal-spec/properties.tex
This PR removes the last traces of the old "reward pot" and renames the "total pot" to "reward pot" int order to match the delegation design spec.  closes #399
=> remove the old reward pot, total pot to reward pot

shelley/chain-and-ledger/formal-spec/address.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex
Adding bootstrap (ie Byron) address to the Shelley ledger spec. closes #391
=> adding bootstrap addresses

byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Update.hs
_Closes issue #262_
Derive a `Semigroup` instance for `PairSet` such that:
> we can define unions of set of pairs in a more convenient way
=> [#262] Derive a Semigroup instance for PairSet

byron/chain/executable-spec/cs-blockchain.cabal, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs, byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, nix/.stack.nix/cs-blockchain.nix, nix/.stack.nix/cs-ledger.nix
_Closes issue #326_
> The delegation map is now injective #292. We could be more explicit about this fact in our code by changing the type of the delegation map from Map VKeyGenesis VKey to Bimap VKeyGenesis VKey, where Bimap can be found here.
>
>Another reason for wanting this is that the operation for finding which genesis key delegated to a given key becomes O (log n) instead of O (n).
=> [#326] Replace Map with Bimap in the delegation state

byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs
Since
```
instance Relation (Map k v) where
...
dom = Map.keysSet
...
```
I figure it makes sense to stick with using `dom` throughout the package where applicable.
=> Use dom function rather than Map.keysSet

byron/chain/formal-spec/blockchain-spec.tex, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/update-mechanism.tex
- Remove epoch change logic from update interface, as this is now handled by the chain spec.
- Reorganize the chain spec so that the related transition system definitions are closer to each other.
- Make the Byron chain and ledger spec match.
- Remove reference to `elens` and make `sEpoch` be an abstract function, to match what we want in the implementation: have the mapping from epoch to epoch lengths be a constant parameter to our validation functions.
- Remove labels from initial rules.
- Add explanations on how to map `upAdptThd` and `cfmThd` to `cardano-sl` protocol paramters.
- Update the voting rule to that the confirmation threshold is passed as an environment variable, and the `UPIVOTE` rule now multiplies `cfmThd` by the number of genesis keys.
- Remove questions as they are no …
=> Split protocol parameters into updatable and non-updateable

shelley/chain-and-ledger/dependencies/non-integer/reference/Makefile
Make compilation and testing easier. Compiles dynamic library and the C++
testing program.
=> [skip ci] Add Makefile for reference implementation

byron/chain/formal-spec/blockchain-spec.tex, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/update-mechanism.tex, byron/ledger/formal-spec/utxo.tex
- Use the protocol parameters from the environment in the block body processing rule
- Use the hash of the UTxO, delegation, and update payload instead of their signature, to align spec with implementation.
- Put the protocol parameters in a single section
Later we can decide whether we move this to the ledger spec. See https://github.com/input-output-hk/cardano-ledger-specs/issues/344
- Add notation for maps and pattern matching in inference rules.
- Add a `UPIVOTES` rules
- Add `UTXOWS` rules
Closes #409 
Close #344
=> Small changes from chain implementation + Jared's feedback

byron/chain/formal-spec/blockchain-spec.tex, byron/ledger/formal-spec/blockchain-interface.tex
The `UPIEC` transition in the Byron ledger spec uses the same interface as all the `UPI...` transitions. In particular, the environment for `UPIEC` includes the genesis key delegation mapping, though it is not used by this transition.  Having a common interface is nice, but `UPIEC` is the only transition not called by the Bryon chain rule `BUPI`, and is thus a bit of a special case.
This PR changes the ledger spec and the chain spec so that `UPIEC` only takes a slot in the environment.
closes #285
=> remove the delegation map from the UPIEC env

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
This PR adds a rule for transitioning from the bootstrap/byron era to a fully decentralized network, as governed by the `d` parameter in the delegation design document.
The `d` value is now a protocol parameter.
The `NEWEPOCH` rule now creates the OBFT schedule using a new pseudorandom function `obftSchedule`, which takes the epoch nonce, `d`, and the active slot coefficient. The schedule is a map of slots to optional genesis keys, where a value of Nothing indicates a non-active OBFT slot.
(Sorry, I am having trouble adding images, I will add them as soon as I figure out what is going on...)
I added a layer of indirection to the `VRF` transition, which in turn calls `BHEAD`. Now there is a new transition `DSLIDE` which calls `VRF` in the case that the slot is _not_ an OBFT slot, and calls …
=> Added a rule for transitioning to decentralization

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/references.bib, shelley/chain-and-ledger/formal-spec/transactions.tex
This PR adds the update mechanisms from the Byron formal specs to the Shelley spec.
The main changes are:
1) The `CHAIN` rule now calls the `UPIEC` rule from the Byron ledger spec to get the new protocol parameters.
2) the protocol parameters have been replaced in serveral spots by `UPIState` (from the Byron ledger spec), which contains the protocol parameters.
3) The transactions now have a new component, the `UpdatePayload`, currently called the `BUPISig` in the Byron Chain spec (but will be changed to match soon).
4) The `LEDGER` rule now processes update payloads in the transactions by using `BUPI` (from the Byron Chain spec) to update the `UPIState`.
Some relevant details about the changes above:
* As a result of the `LEDGER` rule mutating the `UPIState`, the `LState` now contains …
=> using Byron update mechanisms in Shelley ledeger

shelley/chain-and-ledger/formal-spec/chain.tex
This PR adds an explicit function for transitioning the ledger state in Byron to Shelley:
closes #396
closes #435
=> Bryon to Shelley state transition

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
This PR handles the reward payouts during the Byron to Shelley transition.  This is explained in the delegation design document in section 3.9.3.
In particular, two main things were done:
1) the `poolrewards` function that adjusts a pool's rewards by the "apparent performance" now returns 1 whenever the `d` parameter is 0.8 or higher.
2) the `BBODY` rule now takes an additional `oslots :: P(Slot)`  in the environment.  These are the slots of the overly/obft schedule.  The "blocks made" mapping is now only incremented if the slot is _not_ an overlay slot. For this I made a helper function `incrBlocks`.
Additionally, I changed the name of `dsched` to `osched`, since it represents the overlay schedule.
closes #428
=> handle rewards during Bryon to Shelley transition

shelley/chain-and-ledger/formal-spec/chain.tex
as talked about today, this PR makes some changes to the block header body.
Instead of containing a signature of the block body (ie the list of transactions), it now contains 1) the size of the block body, and 2) the hash of the block body.
The `BHEAD` rule now checks that the body size claimed in the header is below the max size as given by the proto params.
The `BBODY` rule no longer needs to check the body signature. Instead, it now checks: 1) the body size given in the header matches reality, 2) the body hash is correct
closes #434
=> block body header has body size and body hash

shelley/chain-and-ledger/dependencies/non-integer/reference/non_integral_test.cpp
The total time was counted twice for the Taylor series based estimation, no functional change.
=> Correct benchmarking for reference

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/delegation.tex
This PR contains several small edits that came up during the big review on May 3, 2019, as explained in #444. (Note that the figure numbers in that issue are all currently off by one, though the names are correct.)
There are two deviations from issue #444:
* I don't think that "prev hash" is actually a better name for the hash in the chain transition state, but is better left described as "last header hash". The value in the state holds the hash of the last block which was validated.  When a new block comes in for validation, we check "previous hash" in the new block against this value we hold in state. yea?
* The issue described as "In Figure 55: BHeader rules, s_0 should be c_0." is more subtle than I thought. I made a separate issue for it: #450
=> small edits from 20190503 review

byron/ledger/formal-spec/notation.tex, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/notation.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
The PR aims to get consistency between the two Byron Specs and the Shelley spec in how protocol parameters are handled. It's pretty minimal.
* Instead of defining `PParams` as a new abstract type, we now reference the Byron ledger spec, so that the type is `PPm |-> Value`.
* The section on protocol parameters now includes all the Byron parameters. I renamed two of the Shelley parameters so that they would match Byron: `maxBHSize` is now `maxHeaderSize`, and `maxBBSize` is now `maxBlockSize`.
* The Shelley spec now computes the min fee like Byron, in terms of the two parameters `a` and `b`.
* The protocol parameters table got too big, so I split off the helper functions off into their own table.
One thing to note is that I did not change the style of using the protocol parameters. In the …
=> using pparams consistently with byron spec

byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/properties.tex, byron/ledger/formal-spec/update-mechanism.tex, byron/ledger/formal-spec/utxo.tex
For the Byron ledger rules, adding hyperlinks to transition tables when one transition is called inside another transition.
=> hyperlinks in byron ledger sub-transitions

byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/update-mechanism.tex
Model the software update metadata.
The `avs` and `raus` component of the state include (abstract) metadata:
The rules where modified accordingly:
Closes #271
=> Model software metadata in update mechanism

byron/chain/formal-spec/blockchain-spec.tex, byron/chain/formal-spec/references.bib
For the Byron *chain* rules, adding hyperlinks to transition tables when one transition is called inside another transition.  (Apologies, I meant to do this along with the Byron ledger rules PR.)
=> hyperlinks in byron chain sub-transitions

byron/chain/formal-spec/blockchain-spec.tex, byron/chain/formal-spec/references.bib, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/crypto-primitives.tex
Previous to this PR, the rules we using two different and conflicting ways to get the start time of an operational certificate: 1) the `KESPeriod` in the cert, and 2) the time associated with the registration of the pool. The second way is completely wrong.
We no longer need `stpools` passed to the header transitions (`BHEAD`, `OVERLAY`, and `VRF`). The `BHEAD` rule now correctly checks the time range of the certificate:
Note also that we added the "superscript KES" notation for verifying KES signatures.
Finally, since it was a small change, this PR also adds the missing check in the `OVERLAY` transition which asserts that the cold key for the given block matches the schedule in the active OBFT rule:
close #450 #446
=> Correct operational certificate start time

byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/update-mechanism.tex
This PR changes the `UPIVOTE` rule, so that the application name to version map is updated with confirmed proposals (before/after):
Closes #463
=> Update app versions when confirmation is stable

byron/chain/executable-spec/cs-blockchain.cabal, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Bupi.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Pbft.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs, byron/chain/executable-spec/src/Cardano/Spec/Consensus/Block.hs, byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs, byron/chain/executable-spec/test/Main.hs, byron/chain/formal-spec/blockchain-spec.tex, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/update-mechanism.tex, byron/ledger/formal-spec/utxo.tex, byron/semantics/executable-spec/small-steps.cabal, byron/semantics/executable-spec/src/Data/AbstractSize.hs, nix/.stack.nix/small-steps.nix
This pull request updates the Haskell implementation of the Byron-Shelley era specification. This started as an implementation of the `PBFT` state transition system, but then that alone wasn't enough to get the whole system working.
I had to make changes to quite a few ledger STSes as well. In particular, can you @dnadales please take a look at all STSes that have `UPIState` as the type of their state? I'm not confident my changes are right.
Closes #364.
There are a few outstanding issues that I would need your help with:
* Clarke pointed out that `upAdptThd` and `t` are the same so use only one.
* Is the `dms` map needed in the `EPOCH` STS? As defined in "Figure 13: Epoch transition rules", I don't see it used anywhere.
* Is it `ProtocolConstants` or `PParams` that an [UTxOEnv …
=> Updates Byron-Shelley era specification implementation

shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This (small!) PR adds a max transaction size to the Shelley ledger rules.  The Byron rules add the check to the `UTXOW` transition, but I thought that putting it in `UTXO` would be more natural for the Shelley rules.
closes #442
=> max tx size check in Shelley ledger rules

shelley/chain-and-ledger/formal-spec/multi-sig.tex
This breaks down the Addr_script type into 3 sub-types which are analogous to
non-script addresses:
- enterprise -> no staking rights
- base -> staking key
- ptr -> pointer address
=> Add possibility for staking in simple multi-sig base on scripts

byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, nix/.stack.nix/delegation.nix, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/Keys.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/PParams.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/Slot.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/chain.tex
`VKey` and `Slot` with conversion functions
`UPIState`
make `cs-ledger` a dependency
=> Import Byron data types into Shelley for `UPIEC` and `BUPI` rules

byron/ledger/executable-spec/src/Ledger/Update.hs
Per issue #471, this fixes the implementation of the `PVBUMP` STS in the Byron-Shelley era. A wrong slot window was considered.
Closes #471.
=> Fixes the Byron-Shelley implementation of the PVBUMP STS

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/formal-spec/blockchain-spec.tex, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/ledger-spec.tex, byron/ledger/formal-spec/properties.tex, byron/ledger/formal-spec/update-mechanism.tex, byron/ledger/formal-spec/utxo.tex, shelley/chain-and-ledger/formal-spec/chain.tex
This PR adds the following property:
This requires the introduction of the reserves in the UTxO state:
The executable specification for UTxO was also brought up in sync with the formal spec. The changes in the spec introduced in this PR were also applied to the executable spec.
Closes #244 
Closes #299
=> Define property: money is constant in the system

shelley/chain-and-ledger/formal-spec/chain.tex
This PR reorganizes the chain-level transitions with the lessons learned from integrating the byron chain-level transitions with the consensus layer.
The main `CHAIN` transition now consists of three sub-transitions (mimicking the Bryon spec): `BHEAD`, `PRTCL`, and `BBODY`. The `BBODY` transition is the same as it was before, but the other two are new.
The **new** `BHEAD` transition include two of the predicates from the old `BHEAD` transition, namely the non-protocol checks that check for sizes. Also new to the `BHEAD` transition is that now it is responsible for all the slot-by-slot upkeep of the system, including calling `NEWEPOCH`, `UPDN`, and `RUPD`:
There were a few problem with the old `NEWEPOCH` that are now fixed:
* there need to be **two** "blocks made" mappings, one for the …
=> reorganizing the chain level rules

weekly-reports/2019-05-31/milestone.org
Here is a minimal first pass at an org-mode file that can track our biweekly progress.
At the beginning of each period, we make an new directory and file, which we update along with PRs as work is completed.
=> [skip ci] org-mode milestone 2019-05-31

cabal.project, iohk-nix.json, nix/.stack.nix/cs-ledger.nix, nix/.stack.nix/default.nix, nix/.stack.nix/delegation.nix, nix/.stack.nix/small-steps.nix, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, stack.yaml
Remove dependency on `tasty-hedgehog-coverage`, coverage and labelling is now supported by `hedgehog` directly.
=> Update Shelley exec spec tests to using `hedgehog` 1.0

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/utxo.tex, weekly-reports/2019-05-31/milestone.org
This PR adds a new component to the transaction for adding extra entropy to the epoch nonce. The new component can only be used by the genesis key holders. The component is a mapping of genesis keys to seeds.
In the UTxO transition, we check that _only_ genesis keys use the component:
In the UTxOW transition we check that all these genesis keys have provided a signature:
The UTxOState maintains the cumulative mapping. Each genesis key is allowed to be linked to one seed per epoch, and if there are at least five such keys in agreement at the end of an epoch, this common value will be used for generating the next epoch nonce.  In order to help with this, there is a new figure with helper functions, three of which are just for dealing with the nested data. The other function, `extraEntropy`, …
=> New transaction component for adding extra entropy

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Consensus/Block.hs, byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs, byron/chain/executable-spec/test/Main.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/semantics/executable-spec/small-steps.cabal, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, byron/semantics/executable-spec/src/Control/State/Transition/Trace.hs, byron/semantics/executable-spec/test/Control/State/Transition/Examples/Sum.hs, byron/semantics/executable-spec/test/examples/Main.hs, nix/.stack.nix/small-steps.nix
- Rewrite the traces generator so that it shrinks properly
- Add an example of a transition system that can be used to: 
- Document how to use our STS framework
- Test the shrinks that we get with our integrated traces-generator
- Re-enable the tests that were disabled in https://github.com/input-output-hk/cardano-ledger-specs/pull/424
Part of #476
=> Rewrite the trace generator

byron/ledger/formal-spec/utxo.tex
Changes:
- The cryptographic primitives specify signing and verifying keys. However I saw that the name spending key was being used in figures 7 & 8 which confused me. 
- In function `addr_h` I believe the hash of the verification key of the input address is being calculated, not the hash of the input address itself.
=> Small adjustment to figure 7 & 8 

shelley/chain-and-ledger/formal-spec/multi-sig.tex
simplify definitions as now a partition of `txins` is used
=> Extend witness type of transaction, move script witness out of transaction body

byron/chain/executable-spec/cs-blockchain.cabal, byron/ledger/executable-spec/cs-ledger.cabal, byron/semantics/executable-spec/small-steps.cabal
For the Byron-Shelley era Haskell code makes a HedgeHog version constraint to at least 1.0.
Closes #505.
=> Makes a HedgeHog version constraint to at least 1.0

shelley/chain-and-ledger/formal-spec/multi-sig.tex, weekly-reports/2019-05-31/milestone.org
moves `mkVKeyHashSet` helper function to appendix
=> Restructure multi-sig example

byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/frontmatter.tex, byron/ledger/formal-spec/properties.tex, byron/ledger/formal-spec/update-mechanism.tex, byron/ledger/formal-spec/utxo.tex
Edits the Byron Ledger spec - adds initial rules for delegation (initial rules already exist for other parts of the spec) - where possible, refer to existing init rules
Issue: https://github.com/input-output-hk/cardano-ledger-specs/issues/477
=> [477] Add Initial State rules for delegation to the Byron spec

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/UTxO/Generators.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/delegation.tex, byron/ledger/formal-spec/frontmatter.tex, byron/ledger/formal-spec/iohk.sty, byron/ledger/formal-spec/notation.tex, byron/ledger/formal-spec/properties.tex, byron/ledger/formal-spec/update-mechanism.tex, byron/ledger/formal-spec/utxo.tex
The `UPEND` rule incorporates a `t` parameter of type `N` (before/after):
And the `UPIEND` rule makes use of this parameter using the floor function and the `upAdptThd` protocol parameter:
Regarding the executable spec these are the changes:
- Remove `PairSet` in favor of a a `Relation` Instance for `Set (a, b)`.
- Add infix operators to give the executable spec a more similar
look to the formal spec.
- Add `nkg` abstract function.
- Change the type of `upAdptThd` from `Int` to `Double`.
Closes #465
=> Fix adoption threshold rules

shelley/chain-and-ledger/formal-spec/multi-sig.tex
first part is now generic for scripts, Plutus and Native scripts became specializations in two separate sub-sections.
=> Restructuring and Correction of Multi-Sig spec

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/chain/formal-spec/blockchain-spec.tex
Issue https://github.com/input-output-hk/cardano-ledger-specs/issues/466
* remove the delegation map `dms` from the EPOCH STS environment
* update the latex spec figures that refer to the Epoch Env (Epoch Transition Types and Rules)
=> [466] Remove dms map from EPOCH STS/latex spec

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Consensus/Block.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXO.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOWS.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/src/Ledger/UTxO/Generators.hs, byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs
This PR removes the `txid` parameter on `TxIn`s that was used for hedgehog state machine testing. We've changed our testing approach to use Traces so we no longer need this!
Closes #531
=> [#531] Remove the txid type parameter from UTxO types

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Ledger/Pvbump/Properties.hs
This patch changes `k` from a global parameter into an STS environment parameter in the Byron-Shelley era executable specification.
Closes #556.
=> Adds k to STS environments in Byron-Shelley

shelley/design-spec/CHANGELOG.md, shelley/design-spec/delegation_design_spec.tex
Clarify that scripts were not supported in Byron, and are not in the first Shelley release either. But do describe how stake rights will work for the future script addresses.
=> Clarify discussion of scripts and script addresses.

byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/test/Ledger/HasTypeReps/Properties.hs, byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs, byron/ledger/executable-spec/test/Main.hs, byron/semantics/executable-spec/src/Data/AbstractSize.hs
Closes https://github.com/input-output-hk/cardano-ledger-specs/issues/523
This PR tests/fixes the HasTypeReps instances for TxWits and related types, along with testing `abstractSize` as it relates to `HasTypeReps`.
=> [523] Test/fix HasTypeReps instances for TxWits and related types

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Core/Generators.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Main.hs, byron/ledger/formal-spec/blockchain-interface.tex, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, nix/.stack.nix/cs-ledger.nix, nix/.stack.nix/default.nix, stack.yaml
- Sync the executable spec with the formal spec:
- We didn't check injectivity of the delegation map
- We didn't check that we delegation epoch didn't lie past the next epoch.
- Fix the implementation of the `SDELEGS` and `ADELEGS` rule, where the
delegation certificates where applied in the reverse order.
- Delete the applied delegation certificates. We used to keep past delegation
certificates. However this led to unexpected behavior where an invalid
certificate would be re-applied resulting in a delegation behavior that was
hard to predict and reason with. 
- Improved the delegation certificate generators:
- Take into account the allowed delegators that can delegate.
- In the tests adapt `expectedDms` so that the injectiviy constraint is taken
into account when applying a sequence of …
=> Add coverage for delegation traces (via DBLOCK transition system)

shelley/chain-and-ledger/dependencies/non-integer/test/Spec.hs
When applied with #587 there are no longer any warnings.
=> Fix warnings in non-integer package

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Ledger/Update/Properties.hs, byron/ledger/formal-spec/blockchain-interface.tex
Update the formal and executable specs for the `UPIVOTE` transition system:
- before:
- now:
In addition the `ngk` global constant is added to the executable specs's environment so that we can test with different values of it.
Part of #550.
=> Align the UP*VOTE formal and executable specs

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, weekly-reports/2019-06-14/milestone.org
This PR fixes an issue with the genesis key delegation mapping. In particular, this delegation mapping caused a violation of a property that we wanted for header validation (see #535 for more information on this property, which has now been written down in the Byron ledger spec).
In addition to the genesis delegation mapping `dms` in the delegation state, we now have a future delegation mapping of type `(Slot x VKeyGen) |-> VKey`. The slot in the first part of the domain's pair represents the first slot when a new delegation can be adopted.
The `DELEG` rule now updates `fdms` instead of `dms`:
The `dms` mapping is updated in the base case of the `DELEGS` rule:
closes #565
=> Issue #565 genesis delegation map header stability

byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Ledger/Update/Properties.hs, byron/ledger/executable-spec/test/Main.hs, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs
- Add a `HasTrace` instance for `UPIVOTES`
- Add coverage testing for the traces that contain update proposal registrations and votes on those update proposals.
Closes #550
=> Add an `UPIVOTES` signal generator 

byron/ledger/formal-spec/update-mechanism.tex
miro PR! :microscope:
`upSTags` definition was missing its parameter
=> small typo with upSTags

shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/update.tex
This PR adds some checks for the protocol version and application versions consistent with the Byron ledger.
The application metadata type `Mdt` is no longer an abstract type, but instead a mapping of `SystemTag` to `UpdateData`, which are two new abstract types.
To provide checks that the protocol versions increase in a reasonable way, I added the Bryon method`pvCanFollow` check to Figure 9.
To provide checks that the application version increase in a reasonable way, I created a new method/predicate `validAV` which calls the Bryon methods `apNameValid`, `svCanFollow`, and `sTagValid`. The `validAV` check is used inside the `newAVS` method, so that only properly increasing versions will be accepted from the `favs`, which is used in figure 10.
closes #572
=> added versioning checks

shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
Addressing the audit marked as April 11, 2019, there are two small changes:
* There is some prose that mentions the `consumed` method that should actually be referring to the `produced` method.
* The naming for the accessor function for the certificates was inconsistent, using both `dcerts` and `txcerts`. now only `txcerts` remains.
closes #614
=> addressing audit comments from April 11, 2019

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Pbft.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs, byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs, byron/chain/executable-spec/test/Main.hs, byron/chain/formal-spec/blockchain-spec.tex, byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOWS.hs, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Core/Generators.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs, byron/ledger/executable-spec/test/Ledger/Core/Generators/Properties.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Ledger/Update/Properties.hs, byron/ledger/executable-spec/test/Main.hs, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, byron/semantics/executable-spec/test/Control/State/Transition/Examples/Sum.hs
- Add a generator for `k` values given a chain length.
- Check that only valid chain signals are generated.
- Remove `stableAfter` from the protocol parameters.
- Have `sEpoch` take the `k` value as parameter.
- Weaken the environment of the chain: `DSEnv` is not needed, only the set of allowed delegators.
- Fix error with initial `sgs` being set to the list of genesis keys, instead of an empty list.
- Change the way block issuers are generated: now only valid issuers are returned (or an error if no valid issuer is found, which means that the block production halted)
- Fix underflow error in `instace STS SDELEG` when calculating the difference between current and certificate epochs.
- Make the delegation certificates generator return only valid delegation certificates.
- Bump the maximum …
=> Make initial environment generators trace-length aware

byron/ledger/formal-spec/crypto-primitives.tex, byron/ledger/formal-spec/ledger-spec.tex, byron/ledger/formal-spec/utxo.tex, shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/PoolParams.hs, shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/Keys.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ocert.hs, shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs, shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/formal-spec/address.tex, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/combined-spec.tex, shelley/chain-and-ledger/formal-spec/crypto-primitives.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/multi-sig.tex, shelley/chain-and-ledger/formal-spec/properties.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This PR renames HashKey to KeyHash across Byron and Shelley specs.
It closes #517.
=> Rename HashKey to KeyHash

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOWS.hs, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Ledger/Update/Properties.hs, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, byron/semantics/executable-spec/test/Control/State/Transition/Examples/Sum.hs
- Modify the types of the `HasTrace`  functions to support generators that can produce failures, and traces with a given failure profile.
- Add a trace profile to `dcertsAreNotReplayed` that allow us to uncover errors in the `DELEG` STS.
Closes #604.
=> Support for invalid signal generation and traces with failure profiles

byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXO.hs, byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs, byron/ledger/executable-spec/test/Main.hs
This pull request implements two properties for UTxO:
* no double spending
* UTxO is outputs minuts inputs
It closes #263.
@dnadales , @uroboros: is there anything to add or change to improve this PR?
=> Adds two UTxO properties

nix/.stack.nix/delegation.nix, shelley/chain-and-ledger/executable-spec/delegation.cabal
Due to a wrong spacing, setting the `development` flag failed building the
project due to disabling many `build-depends`.
=> Fixed use of development flag

.editorconfig, .gitignore, byron/chain/executable-spec/cs-blockchain.cabal, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/test/Cardano/AbstractSize/Properties.hs, byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs, byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/test/Ledger/Update/Properties.hs, byron/semantics/executable-spec/src/Control/State/Transition.hs, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs
=> Add update payload to chain traces

byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOWS.hs, byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs
This PR fixes the order in which transactions are applied in the `UTXOWS` STS in the Byron era.
It addresses one half of issue #655.
=> Fix the order of transactions applied in UTXOWS

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/delegation.tex
This PR introduces a new key pair for the VRF computations (which was previously using the cold keys).
In particular, the pool registration cert now contains the hash of the VRF verification key, the block header now contains the full VRF verification key, the pool distribution now stores both the stake and the registered vrf key, and finally the `VRFChecks` predicate has been changed to:
closes #659
=> Issue: #659 - separate VRF keys

shelley/chain-and-ledger/executable-spec/src/Address.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Tx.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
Add possibility to have mixed vkey and multi-sig payment and staking objects. Add explicit Base and Enterprise type.
=> Add `AddrBase` / `AddrEnterprise` types

shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
Add a second, less trivial, example of applying the top-level CHAIN transition in the shelley exec model.
Unlike the first example, this one applies a block that contains a transaction. The transaction registers a stake key.
Additionally, I've separated the two examples into their own file `test/Examples.hs`.
=> add more complex CHAIN example/test

byron/chain/formal-spec/blockchain-spec.tex
This PR extracts the `EPOCH` rule from `BHEAD`, so we can perform it separately in the consensus layer.
The `BHEAD` rule becomes a simple predicate check:
The `CHAIN` rules change from
to
The Header Only Validation property is also updated to reflect this split.
=> Extract EPOCH from BHEAD

shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/PParams.hs, shelley/chain-and-ledger/executable-spec/src/STS/Bhead.hs, shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/chain.tex
The PR adds two new CHAIN transition examples, and does some syncing with the formal spec.
The first new example adds a block late in the epoch to trigger the creation of a reward update (which is empty, though, since the only PBFT blocks are made).
The second example makes a block in a new epoch in order to trigger a stake distribution snapshot and the application of a reward update.
In terms of modifications to the exec model:
* got `PoolParams` fields in sync
* got `BHBody` fields in sync
* implemented the `overlaySchedule` function with a simple deterministic round-robin schedule that spaces everything out evenly.
=> CHAIN example new epoch transition

shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Bhead.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
This PR adds separate separate VRF keys to the Shelley exec model, as in the formal spec.
It's also does a bit of other syncing with the formal spec, such as tracking the `cCounters` in the pool state.
Three new examples were added, in continuation to the current running example, culmination in the production of a Praos block (ie non genesis key BFT block).
=> Add VRF keys to shelley exec model

shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
I've added three new examples to the Shelley STS tests. These continue the running block by block progress of a new Shelley chain. By this point in the state progression, there is now delegated stake, stake snapshots, and a pool distribution to judge performance of the current epoch.
* example 8 is pretty uneventful, just starting the epoch when the first nontrivial reward update can be created.
* example 9 creates the first nontrivial reward update
* example 10 applies the first nontrivial reward update on the next epoch boundary.
I also made an attempt to make the examples a bit more realistic by having three genesis keys instead of just one.
There was a bit of tweaking/syncing of the exec model. The reward calculation needed to be adjusted to take the pool leader stake from the owners …
=> Shelley examples - non trivial rewards

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/UTxO/Generators.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs, byron/ledger/executable-spec/test/Ledger/Pvbump/Properties.hs, byron/ledger/executable-spec/test/Ledger/Relation/Properties.hs, byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs, byron/ledger/executable-spec/test/Ledger/Update/Examples.hs, byron/ledger/executable-spec/test/Main.hs, byron/ledger/formal-spec/blockchain-interface.tex, byron/ledger/formal-spec/update-mechanism.tex
Fix errors discovered during conformance testing of valid chains against the implementation in `cardano-ledger`.
- Fix the implementation of `PVBUMP`: the last proposal was being taken instead of the first one.
- Simplify the `EPOCH` rule.
- Count the block endorsement when registering it.
- Remove `cfmThd` use `upAdptThd` instead, since these are the same value, and we have no compelling reasons for using different ones here. This closes #623 
- Perform application version change, even when there are not votes in the block.
- Generate the update id's based on the `pwd` set (otherwise we would be generating duplicated proposal id's).
- Add a constant `c` to `GlobalParams` which is used to bound the concrete size. We use this constant when choosing the next `B` factor, and when elaborating …
=> Fix errors discovered during conformance testing

byron/ledger/executable-spec/test/Ledger/Update/Properties.hs
closes #706 
⚠ at least 10% of the update proposals do not change the maximum block-size 39% ██████▊············ ✗ 40%
The above metric has failed once in CI recently, this PR lowers the coverage requirement by 10% for this test
=> [706] Recalibrate coverage metrics

shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Newpp.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Updn.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs
In this PR I have cleaned up the nonces so that the examples are readable. There was one subtlety in the `UPDN` transition that needed fixing. The nonce candidate was not catching up with the epoch nonce after the new epoch transition. The fix was to let the candidate nonce always be set to the evolving nonce in the first rule.
I've added an example of using a protocol parameter update proposal. I needed to change the `NEWPP` transition to clear out the `ppup`s in every case.
I changed the type of `PPUpdate` from `Map Ppm Seed` to `Set Ppm`. This may still not be perfect. In the spec we use a record.
I also changed the `PPUD` transition to use two rules instead of one rule with an `if _ then _ else _`, so that now we have `transitionRules = [ppupTransitionEmpty, ppupTransitionNonEmpty]`. …
=> update proposal example and cleanup nonces

shelley/chain-and-ledger/dependencies/non-integer/test/Spec.hs
* Avoid inconsistencies and repetition: Avoid abuse of (x,x',x'',x'''). Inconsistent use of `normalizeInts` (sometimes swapped, others not).
* Simplified expressions. Factorized common code patterns. Try to use the same notation conventions throughout all code.
* No need to check `(x > 0)` for `(Positive x)` as the QuickCheck type guaranties just that.
* Added Arbitrary instance for interval `[0,1]`
* Generic polymorphic properties defined in one place. Then, particularize generic properties for each concrete type (FixedPoint, Double, Rational).
* Notation change: Use "Pow" for `x^y` to avoid confusion with "Exp" for `exp`. Name "lnLaw" as a law analogous to "ExpLaw", ...
* Added property for logarithm law: `ln(x · y) = ln(x) + ln(y)`
* Missing `abs` in comparison to *epsilon* in props: …
=> Rewrite of the non-integer test code and some fixes.

shelley/chain-and-ledger/formal-spec/non-integral.tex
Use 'approx' versions of operators in non-integral formulas.
=> Errata non-integral.tex : approx in properties' formulas

shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs
The first two commits in this PR do a bit of clean-up:
* I've made constructing and using all the pool keys easier, and replaced all the individually named genesis keys with a list of seven (bye-bye Gerolamo).
* I've renumbered the examples so that it is easier to see which one are continuations of the other ones (so `2A`, `2B`, `2C` instead of `3`, `4`, `5`, etc)
I've implemented the `votedValuePParams` method so that the `EPOCH` rule will now update the protocol parameters when appropriate.
I've added tests for a successful protocol parameter update.
closes #713
=> Examples for a successful protocol parameter update

nix/.stack.nix/delegation.nix, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/update.tex
This PR adds examples showing how the application versions are updated. While writing the example, I uncovered and fixed a problem with the `AVUP` transition in the formal spec.
The problem was that the future adoptions were only getting accepted when a block was processed that 1) had at least one transaction, and 2) contained an app version update. But we want to adopt future versions as soon as possible!
Therefore I have moved this logic into the base case of the `LEDGERS` transition. To be specific, the base case of the `LEDGERS` transition now cleans out the old "future application versions" and updates the current app versions when appropriate.
closes #719
=> add examples for AVUP and fix AVUP

shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/non-integral.tex
This fixes an error in the refund calculation, effectively it used `(d + (1 - d)) *exp(x)` instead of `(d + (1 - d)*exp(x))`. Also the `fpEpsilon` constant was wrong, making all decay instantaneous.
This also adds examples for different ways to use 
- no decay
- instant decay
- full refund (minimal refund 100%)
=> Fix error in refund calculation

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
Closes #731 
* add missing predicates from exec. spec (txize <= maxTxSize + coins are all positive)
* add a Relation instance for `UTxO hashAlgo dsignAlgo`
* general refactoring of UTxO STS to more closely match formal spec
- more inline functionality (e.g. replace `validNoReplay tx` with `txins /= empty`) 
- update STS state with record syntax (instead of using lenses)
@mgudemann With the maxTxSize predicate added, the MultiSig examples were failing since it was using `emptyPParams` (with maxTxSize = 0) to run the STS step.
I added an `initPParams` (with maxTxSize = 1000) to be used in the multi-sig examples (the examples were producing Tx's with size roughly around 400-600)
=> [731] Sync executable with formal spec - UTXO STS

shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Up.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/formal-spec/update.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
While syncing the `PPUP` transition in the exec spec with the formal spec (ie, adding the two missing predicates), I found two problems with the formal spec.
First, since a protocol proposal update (`ppup`) is a _mapping_ of (soon to be hashes) of genesis keys to a mapping of new protocol parameters, the `pvCanFollow` check needs to be done for every element of the range of a `ppup`, not just once on the whole `ppup`.
Second, the `pvCanFollow` check needs to be compared against the current protocol version in the protocol parameters, not against the staged votes. This means that the `UP` and `PPUP` transitions both needed the protocol parameters added to the environment.
As for implementing the two needed predicates, one was straight-forward, but the other was not quite as expected. I …
=> Sync executable with formal spec - PPUP

shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/update.tex
it is now easy (I think/hope) to compare `AVUP` transition between the formal spec and the executable model.  in the process, I found some bugs, fixed some bugs, and cleaned things up.
There was a problem with how the future application versions were being moved into the current application versions. The problem was that we were only taking the most recent pending update that was below the current slot, which is not correct since that update may, for instance, only increase one application. The `AVUP` helper functions now look like:
I have moved the checks on the application version updates from the point in time when they are put into the current application versions to the point in time when the proposals first come in (ie in `AVUP`).
Regarding these checks, I have added a `TODO` to …
=> Issue #730 - sync AVUP

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/update.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This PR address some small typos from four different issues
Make the case distinction in the `RUPD` transition proper
closes #742
Address half of  #744 (the formal spec part, namely that `sigma` and `tau` were swapped)
Fix all the bleeding italics (and catch two typos).
closes #775 
Address several typos from the recent audit report on 2018-08-16.
closes #778
=> typos and small fixes

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BBody.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXO.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/semantics/executable-spec/src/Control/State/Transition.hs
Add comments on `PredicateFailure` data declarations.
Rename a few constructors, adding a `S_` prefix to indicate their
structural-ness.
Document the convention in the class definition.
=> Document throwable vs structural `PredicateFailure`s

byron/ledger/executable-spec/src/Ledger/Core.hs, shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/delegation.tex
The `DELEG` transition now properly removes the stake registration certificate pointers on the de-registration of a key.
I added the range exclusion operator (`⋫` or `|/>`) to the `Ledger.Core` `Relation` class.
Both the formal spec and the exec model now remove the cert prt with `ptrs ⋫ {hk}`.
I found another small fix, namely the `UTXO` rule was not allowing zero-valued coins, so now it does.
I added an example (`2J`) which drains a reward account and then de-registers a stake key.
unrelated to the main issue, I made the protocol update example (example 3) a bit more interesting by also voting on extra entropy. This value is a bit special, since after a successful vote, it injects itself into the next epoch nonce and is then set back to the neutral element in the protocol parameters. …
=> remove stake cert pointers on dereg

shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs
This PR cleans up a couple problems with the pointer addresses.
* The pointer addresses needed a payment object.
* The function that computes the stake distribution, `stakeDistr`, was taking a union of the three places where stake lives: base addresses, pointer addresses, and reward accounts. The problem with this is that `Map.union` a union-override-left, but really we need a union-override-plus. In the formal spec with use the relational `aggregate_+`, which I think is implemented well  in Haskell with `Map.unionWith (+)`.
closes #783
=> polishin' the pointer addresses

shelley/chain-and-ledger/formal-spec/address.tex, shelley/chain-and-ledger/formal-spec/crypto-primitives.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/multi-sig.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This merges the stand-alone multi-sig spec into the Shelley spec, with the native multi-sig scripts as implementation choice for Shelley. The separate spec will be kept, in order to show how different multi-sig approaches and more general, how scripts can be integrated into the ledger rules.
=> Merge multi-sig specification into Shelley spec

shelley/chain-and-ledger/formal-spec/appendix.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/properties.tex
Adapt the properties in the Shelley spec to better match the current STS rules.
The properties currently use custom generators instead of STS based generators, therefore they are still valid.
=> Adapt properties for new STS rules

shelley/chain-and-ledger/executable-spec/src/STS/Delpl.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs
Closes #734 
NOTE I'm re-defining the Relation-operators Union and Union Override in this STS since we lack an ORD instance for `PParams`. 
If it makes sense to pursue that ORD instance, I can tighten this code some more (and use the Relation operators)
=> [734] POOL STS - sync exec. spec with formal spec

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Up.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/update.tex
I've updated the exec spec so that the Metadata in the apps are now a mapping of system tags to installer hashes. And now we validate the system tags as well (both in the formal spec and the exec model).
closes #808 
closes #615
=> Issue #808 Metadata is map of tags to installers

shelley/chain-and-ledger/executable-spec/src/STS/Ocert.hs, shelley/chain-and-ledger/formal-spec/chain.tex
Closes #743 
Closes #744 
For #743 (BHEAD STS) I changed the following in the formal spec:
* I added the missing assignment `(_,_,_,pp) := es` (@JaredCorduan this might ring a bell - we previously had `(_,_,_,es) := es` in the formal spec, which was incorrect and then removed.)
* in the exec. spec, `ru` was being destructured from `nes'`,  rather than `nes`. I added an assignment of ru from `nes'` (Note: the exec. spec tests failed when I tried to conform to the formal spec's ru assignment from `nes`)
=> [743] [744] BHEAD + OCERT STS's - sync formal and exec. specs

shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/Keys.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/src/Tx.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/ledger.tex
There were a few issues all related to the genesis key delegation that this PR addresses.
* There were some fields in the delegation certificates that needed to be `KeyHashes` instead of `VKeys`. In particular, the genesis delegation cert and the pool registration had this problem.
* The type for witnesses, `WitVKey`, did not allow for genesis key witnesses.
* The genesis key delegation mapping had the same problem that previously existed with the application versions, namely that it is not updated when there are no transactions in the block. The solution was the same, move this updating of the maps to the `LEDGERS` transition. This was a change in both the spec and the exec model.
There's now an example for re-delegation of a genesis key.
closes #792
closes #793 
closes #798
=> Issue #792 #793 #798 key hashes and genesis deleg

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs
Closes #740 
This brings the leader reward calculation in the exec. spec in line with the formal spec. This means some hardcoded coins in the examples needed to change
=> [740] UPDN STS - sync formal and exec. spec

shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs, shelley/chain-and-ledger/formal-spec/properties.tex
Implement properties for checking delegation certificates used in the `DELEG` STS rule.
Checks that:
* Credential deregistration correctly removes the credential from the mappings
* Credential delegation correctly changes the delegation mappings
=> Adapt  and implement `DELEG` STS rule properties

shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/ledger.tex
The genesis delegates (ie the cold keys that the genesis keys delegate to) are not registered like normal stake pool keys, and were not previously being given initial counters for the operational certificates. Now the `toShelley` method in the formal spec sets a counter of zero for each starting genesis key delegate.
Additionally, while making this change, I noticed a couple related things that also needed fixing:
* We should not allow two different genesis keys to delegate to the same cold key. There is now a check for this.
* When re-delegating a genesis key, the old delegate needs to be removed from the op cert counters.
closes #643
=> initial genesis key op cert counters

shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs
Needed to call this from ouroboros-network.
=> Expose details from PRTCL

shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestPoolreap.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/Makefile, shelley/chain-and-ledger/formal-spec/epoch.tex
There were a couple of problems with the pool certificate refunds in the `POOLREAP` transition.
First, the sum total of the (claimed and unclaimed) refunds that was handed out was not deducted from the global deposit pot. In fact, the `UTxOState` wasn't even in scope. Therefore I added the `UTxOState` to the `POOLREAP` state in both the formal spec and the exec model, and the appropriate amount is removed from the deposit pot.
Second, the slot duration given to the refund calculation was incorrect.  For the current epoch `e`, it was calculating `firstSlot e - firstSlot e` for every duration. In other words, the full refund was always being handed back. The fix was to get the slot when the pools were registered from `stpools`.
I added new tests. For each example in `test/Example` there is …
=> fix pool cent refund accounting

shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestUtxow.hs
This adds the UTXOW properties in the formal spec in the form of STS based properties. Currently they are not yet tested as the generators are currently `undefined`.
=> STS-based properties for UTXOW

shelley/chain-and-ledger/formal-spec/chain.tex
We only use sets of key hashes.
=> The `BHEAD` rule used `Set VKeyG` in its environment

.gitignore
Used by `cabal v2-*` commands.
=> Gitignore .ghc.environment

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs, byron/ledger/executable-spec/src/Ledger/Update/Test.hs, byron/ledger/executable-spec/test/Ledger/Update/Examples.hs, cabal.project, nix/.stack.nix/goblins.nix, stack.yaml
Closes #788 and #817. 
This prepares for a PR to `cardano-ledger` which integrates goblins into the conformance tests.
We modify some Goblin instances here to be aware of certain bounds which were not encoded in the types (but were captured, for example, by the valid hedgehog generators).
=> Integrate goblins into the conformance tests

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, byron/semantics/executable-spec/src/Control/State/Transition/Trace.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs
- Define `lastSignal` and `traceInit`, which are needed for #787
- Use `ofLengthAtLeast` in the Shelley delegation tests.
- Add `isHeaderSizeTooBigFailure` function.
=> Define `lastSignal` and `traceInit`, which are needed for issue 787

byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/Address.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Bbody.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
Closes #844 
* generates transactions as LEDGER signals (the LEDGER STS level is the lowest level that provides enough context to generate meaningful certs)
* occasionally generate a RegKey DCert for a Tx
* tests the `rewardZeroAfterReg` property using the LEDGER trace
* classifies the LEDGER STS Trace (w.r.t the generated data so far)
NOTES: 
* This PR forms the basis of a series of PRs that will incrementally test properties against the generated LEDGER Tx/Certs. (Each new property test will place new demands on the generators.)
* Generators.Core.hs in this PR is harvested from @mgudemann 's pre-STS property test generators. Over the course of a few PR's, we will remove the pre-STS generator code in favour of Generator.Core and Generator.*
* the classify-trace tests are inspired by …
=> [844] First draft trace generator for LEDGER STS, testing first Shelley property

shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestUtxo.hs
Adds properties from the `Properties.md` file
- the fees are non-decreasing
- the sum of the pots circulation / deposits / fees increases with the sum of the withdrawals
=> Propertyies for `UTXO` STS rule

shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs, shelley/chain-and-ledger/formal-spec/Properties.md
```
Pots in scope: Rewards
**Property** The rewards to do not change (both as an aggregated value
and as individual balances).
```
in addition, elements added or dropped (via RegKey or DeregKey) have a zero reward balance
=> Add property to check for rewards balance invariant in `DELEG`

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs, byron/chain/executable-spec/test/Main.hs, byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Ledger/Core.hs, byron/ledger/executable-spec/src/Ledger/Delegation.hs, byron/ledger/executable-spec/src/Ledger/Delegation/Test.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/executable-spec/src/Ledger/Update/Test.hs, byron/ledger/executable-spec/test/Ledger/AbstractSize/Properties.hs, byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs, byron/ledger/executable-spec/test/Ledger/Update/Properties.hs, byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs, byron/semantics/executable-spec/src/Data/AbstractSize.hs, cabal.project, nix/.stack.nix/goblins.nix, stack.yaml
In this way we can signal to elaborators that they should produce an invalid (concrete) hash.
Part of #787
=> Change hash type to Maybe Int

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/crypto-primitives.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/update.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This PR combines several small edits.
* I removed the `SlotsStabilityParam`.
* I added new global constants, `MaxKESEvo ` and `Quorum`, and put all constants in the protocol parameter section (so I moved `SlotsPrior` and `StartRewards`.
* few white-space edits
* changed N^+ to N^{>0}
* consistent multiplication and division symbols.
* moved update system explanations in the transaction section to the update section.
* added a few extra prose descriptions.
* fixed the typo @nc6 found today, we now have `oldGenDelegs </| cs`.
closes #827
closes #830
closes #833 (this one looks to have been completed by an earlier PR, but I checked)
=> several small edits

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Bbody.hs, shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delpl.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
Adds different examples for MIR
- creating instantaneous rewards
- rejecting MIR because of insufficient core node signatures
- rejecting MIR because of `d = 0`
- rejecting MIR because of both of the above
- rejecting MIR because of insufficient reserves
=> Add MIR examples

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs, shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs
- add example that transfers instantaneous rewards.
- fix `createRupd` function
=> Add example for MIR application

shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/properties.tex
this PR adds the full `preservation of value` property to the formal spec, and gives a proof. note that the proof does not depend on a definition of initial state.
closes #953
=> preservation of value property and proof

byron/ledger/executable-spec/cs-ledger.cabal, byron/ledger/executable-spec/src/Hedgehog/Gen/Double.hs, byron/ledger/executable-spec/src/Ledger/Update/Generators.hs
AUX is a reserved file name on Windows.
resolve #961
=> Renamed Hedgehog.Gen.Aux to Hedgehog.Gen.Double

shelley/chain-and-ledger/executable-spec/test/Rules/TestPool.hs
In #870 I added a check for adding new pools. In this PR I add a small additional check for re-registering pools once they've been `DeReg`ed, and thus added to the `retiring` set.
=> Add `RegPool` re-reg properties

shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs, shelley/chain-and-ledger/formal-spec/epoch.tex
This PR syncs the changes to the POOLREAP transition with the changes recently made in the formal spec: #976 
It now looks like this:
=> sync POOLREAP with formal spec

shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
- a MIR certificate an now only be applied if all contained stake credentials have been registered
- the reward update creation does not change the deposit anymore (no new stake credential registrations)
- the reward update application only takes into account the rewards paid to registered stake credentials, all non-registered ones are paid back to the reserves
=> Redesign MIR scheme

shelley/design-spec/delegation_design_spec.tex
As discussed yesterday, we do not want to require a witness from the private stake key for registering the key. The only reason we had for requiring one was to prevent people from registering a key they do not own (and they can still end up in the same situation if they lose the key after registration). Not requiring a witness makes the reward transfer from the incentivised testnet easier.
Also, I fixed the appendix (which was out of data, and still said it was to be decided whether stake in reward accounts was considered active).
=> Design doc: Do not require witness for stake key registration.

shelley/chain-and-ledger/formal-spec/delegation.tex
Was key hash in the spec, should be stake credential.
=> Correct type of `ptrs` map in `DState`

shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/properties.tex
We simplified the instantaneous reward mechanism in #995. We no longer automatically register stake keys that are in the MIR cert but are not yet registered. This simplifies the reward update calculation. In particular, it doesn't touch the deposit pot anymore.
This PR adapts the changes above the the proofs in section 15 for "preservation of ada" and "non-negative deposit pot".
closes #997
=> fixing the property proofs after MIR adjustments

shelley/chain-and-ledger/formal-spec/properties.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
replaces #1021 in order to get a buildkite build
=> Fix: misplaced parens in deposits function (formal spec)

shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs
replaces #1028 in order to get a buildkite build
additionally addresses a point of confusion mentioned in #1028, namely the use of union instead of union override. the function `updatePPup` was calling union with the order of the parameter swapped, so it was in fact correct, but perhaps confusing. I've removed `updatePPup` entirely and just use union override directly in the STS rule.
=> Fix: predicate of PPUpdateTooLatePPUP (exec spec)

nix/.stack.nix/delegation.nix, shelley/chain-and-ledger/cddl-spec/shelley.cddl, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/Coin.hs, shelley/chain-and-ledger/executable-spec/src/Keys.hs, shelley/chain-and-ledger/executable-spec/src/Serialization.hs, shelley/chain-and-ledger/executable-spec/src/Slot.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs, shelley/chain-and-ledger/executable-spec/test/Tests.hs
This PR makes some adjustments to how we serialize the Shelley transactions, and includes several tests that can be used to see exactly what CBOR tokens are generated in the various situations. The new tests are found in `shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs`.
Additionally, this PR adds a cddl file, which is still a work in progress, but that I think is worth including as a roadmap.
closes  #1015
=> CBOR serialization adjustments of Shelley txns

shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
I believe this was broken when I merged https://github.com/input-output-hk/cardano-ledger-specs/pull/1038.
=> Fix module broken by merge

byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs
Closes #872 
Closes  #1039 
This PR
* generates Delegate certs (using QuickCheck)
* classify the trace to ensure that Delegate certs are being produced
* switch the LEDGER Trace Classifier to QuickCheck from Hedgehog (HH was still being used here due to #1039 which is resolved by this PR) 
@mhuesch #1039 had to do with the fact that the LEDGER STS needs an initial state but does not have an Initial Rule to produce that state, so we have to provide an Initial State generator. I amended the STS machinery to allow for this. 
(hence the error "applySTSIndifferently was called with an empty set of rules", which is trying to produce the initial state from an initial rule)
=> [872] Generate Delegation Certificates

shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/src/STS/Updn.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/formal-spec/chain.tex
The `UPDN` transition now stores the hash of the last block header of the previous epoch so that it can combine this with the next epoch nonce created.
closes #1058
=> adding the last hash in prev epoch to nonce

shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Tests.hs
This activates generation of MIR certificates in the tests. Valid signals require full signature and non-zero `d`
=> Generate MIR certs

shelley/chain-and-ledger/formal-spec/utxo.tex
micro PR, the `consumed` function does not need to be passed the `Wdrls` parameter. This error is only in the formal spec, not the exec model.
=> consumed does not use rewards param

nix/.stack.nix/delegation.nix, shelley/chain-and-ledger/executable-spec/Makefile, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Coin.hs, shelley/chain-and-ledger/executable-spec/src/Keys.hs, shelley/chain-and-ledger/executable-spec/src/OCert.hs, shelley/chain-and-ledger/executable-spec/src/Serialization.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Tests.hs
This PR adds `FromCBOR` instances to match all our recent `ToCBOR` instances. The `checkEncoding` tests now also check that the serialization round trips correctly, in the sense that `fromCBOR . toCBOR` is the identity (we can soon turn these into property tests as well).
=> FromCBOR instances and tests

shelley/chain-and-ledger/executable-spec/src/Address.hs, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delpl.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/Tx.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/MockTypes.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestPool.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
This restructures certificates a bit, grouping into Deleg / Pool / Genesis and Mir in order to have cleaner functions, e.g., `cwitness`. This should help with generators as genesis and mir certs are conceptually different from the others.
=> Restructure certificates

shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Shrinkers.hs
Closes #1083 
* `genInstantaneousRewards` was producing empty certificates (`InstantaneousReward {}`) when no stake credentials are available, in this PR we discard such certs
* `genInstantaneousRewards` now discards generated certs when d=0 (full decentralisation mode)
* with that in place I could generate PParams with d=0 again
=> [1083] Allow full decentralisation in generators

shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/properties.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
@javierdiaz72 's recent work to formalize the "preservation of ada" property of the Shelley ledger spec (ie section 15.1) has revealed some improvements, which this PR adds:
* The protocol parameters are now fully defined in the Shelley spec (instead of just referencing the Byron spec)
* The hand proof of "preservation of ada" in section 15.1 makes it clear that the "non-negative deposits" comment is not needed for the proof (but is just nice to note)
* In the exec model, in the places where a pattern match is used instead of a named accessor function used in the spec, a comment is added.
* The domain of the `regCred` function was fixed (regkey instead of regpool).
* The range of the `cwitness` is fixed (not a powerset anymore).
* New reward accounts are now created with union override …
=> Minor edits to the Shelley ledger formal spec

byron/ledger/executable-spec/src/Ledger/Core.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delpl.hs, shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/STS/Newpp.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/src/STS/Up.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
I went through the formal and exec specs today, line by line, comparing them.  In order of the formal spec, I made it through the end of the `EPOCH` rule. This PR is comprised mostly of trivial changes to get the two specs in sync.
The majority of the changes are 1) renaming variables, and 2) reordering the order in which things are defined and predicates checked.  In order to have the same variable names between the specs, I made a lot of use of relative imports in the haskell code (LedgerState.hs was the biggest culprit).
Other notable changes:
* the `AVUP` rule was using union override right, but in the wrong order.
* the ledger state does not need to store the index of the transaction being processed. this is a artifact from the `asStateTransation` method still  being using in the …
=> syncing formal and exec specs

byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs
Closes #1084 
This PR 
* fixes a bug in the trace shrinker (signals were passed in OldestFirst order to `Trace.closure` which expects NewestFirst)
* write a custom shrinker signal shrinker (replaces shrinkList) that preserves the leading signal during trace shrinking
This PR was intended to close #1084 which was about improving the Tx shrinker. On closer inspection the next bottleneck was _trace_ shrinking - since at this stage we're only producing Txs with single certificates and outputs, the options for shrinking are very limited. 
The remaining Tx shrinking work should be done as part of #868 and #877 (when we add multiple certs we can shrink them in a Tx, same with outputs)
=> [1084] Fixed and improved trace shrinker

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestUtxow.hs, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/properties.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
There was a state variable and a function both named `deposits`. I have renamed the function to `totalDeposits`in both the formal spec and the exec model.
I think this is the only such remaining variable name like this. closes #980
=> change function name deposits to totalDeposits

shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
Some functions in `Delegation.Certificates` were redundant or unused.
A comparion in a coverage test was flipped.
=> Removes some redundant / unused functions, correction of predicate

shelley/chain-and-ledger/formal-spec/chain.tex
The type of a reward updates is a maybe type, but  `applyRUpd` takes a pure value. Therefore the `NEWEPOCH` rules needed a new rule/case for the Nothing update.
closes #577
=> NEWEPOCH transition to do nothing on Nothing

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/formal-spec/chain.tex
The formal spec now explicitly defines the valid initial Shelley ledger states, and the test/examples use such valid states.
The previously defined `toShelley` function used to take a Byron state as input, but now it is explicitly passed only the data it needs. Valid initial Shelley ledger states are now defined as the range of this function. The function is renamed as `initialShelleyState`, and a new function `toShelley` converts a Byron state to a Shelley state by the appropriate call to `initialShelleyState`.
The new `initialShelleyState` does a couple things the old function did not (besides fixing a few errors). It now is passed an epoch (instead of calculating it) so that we do not need to use the global constants, and it is also passed and sets the overlay schedule.
closes #840
=> explicit initial shelley ledger states

shelley/chain-and-ledger/executable-spec/src/Tx.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestUtxow.hs
Some of the required combination of keys must be a subset of the witnesses of
the transaction for all multi-sig scripts of each transaction.
=> Add property for MSig

shelley/chain-and-ledger/cddl-spec/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
This PR adds a realistic abstract size function for transactions based on our cddl file. The purpose of the function is to be a reasonable bound on the number of bytes.
There are still a few remaining details to iron out regarding incorporating the non-body components of the transaction into the fee. This will be incorporated with the resolution of #812 
closes #298
=> abstract transaction size function

cabal.project, nix/.stack.nix/cardano-binary.nix, nix/.stack.nix/cardano-crypto-class.nix, nix/.stack.nix/cardano-slotting.nix, shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/Keys.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/PParams.hs, shelley/chain-and-ledger/executable-spec/src/Serialization.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, stack.yaml
This PR adds all the necessary `ToCBOR` and `FromCBOR` instances needed to be able to serialize `NewEpochState`.
We do not intend to send this data over the wire, these instances are needed for local storage.
The work was mostly manual and straightforward, but there are a few things worth mentioning:
* I added a `FromCBOR` instance for the `CBORGroup` class.
* I put in some TODOs for reconsidering how we serialize `Coin`. We currently do not ever want anyone to send a negitive value on the wire. Therefore we are using `Word`. This will change, however, with Plutus (eg, forging negative amounts of currency). Moreover, there are two places in the ledger state where the coin values are _always_ non-positive (both in the reward updates, where we record how to reduce the reward pot and the fee …
=> cbor instances for NewEpochState

shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API/Mempool.hs, shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delpl.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Up.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs
This PR add more (de-)serialisation needed for the integration with consensus, namely everything needed for `ApplyTxError`.
=> CBOR instances needed for ApplyTxError

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/ledger/executable-spec/src/Ledger/Core/Generators.hs
The generator for `k` in `Ledger.Core.Generators` sometimes generated `k = 0`. This was documented behaviour, but unfortunately some of the the other generators in the ledger spec could not deal with this. Two examples:
```haskell
-- | Compute the epoch for the given _absolute_ slot and chain stability parameter.
sEpoch
:: HasCallStack
=> Slot
-> BlockCount
-> Epoch
sEpoch (Slot s) k = if k' > 0
then Epoch $ s `div` k'
else error ("sEpoch: bad `k` provided: " <> show k)
where k' = slotsPerEpoch k
```
and the computation of the PBFT threshold
```haskell
sigCntT :: BlockCount -> Word8 -> Gen Double
sigCntT (BlockCount k) ngk =
Gen.double (Range.constant lower upper)
where
lower = 1 / (fromIntegral ngk * 0.7) + 1 / fromIntegral k
upper = 1 / (fromIntegral ngk * 0.5) + 1 / fromIntegral k
``` …
=> Don't generate `k` equal to zero

byron/ledger/executable-spec/src/Ledger/Core.hs
- Add ToCBOR instance for newtypes in `Ledger.Core` that didn't have one.
- Define `+.` as an alias for `addSlot`.
=> Add more ToCBOR instances to Ledger.Core

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
Since adding the multi-sig scripts, there can be more signatures than required by the vkey witnesses. Ti Disincentivize addinging redundant signatures, we include the witnesses and multi-signature scripts in the transaction size calculation.
=> Include witnesses in transaction size calculation

shelley/chain-and-ledger/executable-spec/src/STS/Newpp.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/properties.tex
This PR addresses several issues that arose from the Isabelle formalization (the third installment :) ). The main issue to be resolved was #1146, but in the process we learned more than was mentioned in the issue on github. In fact, all that was needed was the extra predicate `deposits == obligation` in the `NEWPP` rule. (The explanation is: The stake pools which will be reaped during the `POOLREAP` transition must still be a part of the new snapshot, and so `SNAP` must occur before `POOLREAP`. Moreover, `SNAP` sets the deposit pot equal to current obligation, which is a property that is preserved by `POOLREAP` and which is necessary for the preservation of Ada property in the `NEWPP` transation.)
Several small issues/typos were fixed:
* remove some abusive notation, which was using union …
=> small shelley ledger spec edits from isabelle review #3

byron/semantics/executable-spec/test/Control/State/Transition/Examples/CommitReveal.hs, byron/semantics/executable-spec/test/examples/Main.hs
- Increase the number of tests to run in `prop_qc_OnlyValidSignals`
- Increase the length of the trace (this will increase the chance of finding a
duplicated submission)
- Reduce the test space (id's are taken from the interval `[-2, 2]` instead of
`[-10, 10]`).
=> Fix brittle tests in small-steps

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
The implementation of `overlaySchedule` in the shelley exec spec needs to return an empty map when `d=0`, otherwise there is a divide by zero.
=> fix overlaySchedule in the case when d is zero

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/properties.tex
This PR simplifies the `createRUpd` function. This makes the function both easier to understand and easier to prove things about.
Prior to these changes, `createRUpd` was filtering out the instantaneous rewards for all those stake keys that were not registered, and saving this filtered mapping in the reward update. The `applyRUpd` function would then further filter the map, since between the time the reward update was created and when it was applied, stake keys could have been deregistered. We now skip the filtering of unregistered keys in the creation of the reward update. We do, however, still store the instantaneous rewards in the reward update. Though we do _not_ expect the instantaneous rewards mapping to change (as it is frozen during the end of an epoch), using the stored mapping …
=> simplify createRUpd (both formal spec and exec spec)

shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
This uncovered two functions in the executable spec that didn't cover all relevant cases
- `getScriptHash`
- `txinsScript`
=> Generate pointer addresses

byron/semantics/executable-spec/src/Data/AbstractSize.hs
- Add `Word`, `Word8`, `Word32`, and `Word16` instances of `HasTypeReps`.
=> Add more WordX instances for HasTypeReps

shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
Closes #1113 
Generate OCerts as part of block headers. Also adds a property test to validate the blocks we are creating as signals of the CHAIN trace. 
As it stands the block validation fails for traces that are longer than 10-20 blocks, due to InvliadKESSignature predicate failures - see new issue  #1173 
Other issues addressed by this PR: 
* when generating MIR certs, we suppress generation when it is too late in the epoch for valid MIR certs
* BUG fixed: `genTx` was using the previous chain slot and leading to ValueNotConserved  predicate failures
* `mkGenesisChainState` now uses `initialShelleyState`
=> [1113] Generate OCerts and valid blocks (for short traces)

shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Up.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/update.tex
In order to avoid the situation where a transaction can go from being invalid to valid while sitting in the mempool, we now require that nonempty protocol parameter updates specify the epoch in which to process them.
The `Update` type now includes an optional epoch number. The signal for the `PPUP` rule is now a pair of a `ppup` and an optional epoch number. In `PPUP`' if the mapping `ppup` is non-empty, then we check that the epoch number in the signal is equal to the current epoch.
Originally I tried putting the optional epoch number in the protocol parameter update type itself, but this turned out to be more disruptive.
closes #1111
=> updates can now specify target epoch

nix/.stack.nix/cardano-binary.nix, nix/.stack.nix/cardano-crypto-class.nix, nix/.stack.nix/cardano-slotting.nix, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, stack.yaml
requires input-output-hk/cardano-base#68
=> Use abstract size of vkeys and signatures in `txsize`

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs, byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs, byron/ledger/executable-spec/src/Ledger/UTxO.hs
See https://github.com/input-output-hk/cardano-ledger/issues/698#issuecomment-578726113 for a detailed description of the bug this fixes. 
Before the fix, no regular transactions were being generated at all. After the fix, in 7% of test runs the average number of txs per block is still 0, but  in in 29% of test runs the average number of txs per block is 1, and in 59% of test runs the average is more than 1. 
Note that the situation for other kinds of transactions (delegation certificates, update proposals and update votes) already looks good and does not seem to require a similar kind of fix. 
```
trace length: empty       3% ▌···················
avg # tx == 0            97% ███████████████████▍
min # tx == 0            97% ███████████████████▍
max # tx == 0            97% …
```
=> Make sure CHAIN generator produces transactions

shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestChain.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestNewEpoch.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestPoolreap.hs
Closes #1134 
Closes #1136 
Closes #1137 
Closes #878  
When wiring up these properties,the following 2 failed: 
* POOLREAP.removedAfterPoolReap - removed a clause that required an empty retired set ` (not . null) retire`
* NEWEPOCH.rewardDecreaseEqualsTreasuryRewardPot - added deposits and utxo balance to the invariant - this was neccessary due to the fact that the pre/post states we're testing the NEWEPOCH STS with is derived from the pre/post states of the CHAIN STS and because of that includes effects from other STSs, not just NEWEPOCH in this case
=> [1137] Wire up PoolReap and NewEpoch properties to CHAIN trace generator

shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
This PR removes the restriction that `d=1` and `f=1` during the chain trace generation. We still do not allow `d=0` and `f=0`. The case when `d=0` requires ensuring that there are active stake pools (otherwise the chain deadlocks). The case when `f=0` is problematic if there is an overlay schedule (and is degenerate anyway, since this means no one can ever win leader election).
In order to validate chain traces while varying `d` and `f`, we use the overlay schedule to guide the selection of the next slots used for the blocks.
A couple of problems were found with the overlay schedule creation function. They have been fixed.
This work also uncovered a problem with the creation of reward updates, see #1187. The `CorruptIRWDs` error/check has been removed (in the exec model, not the formal …
=> Vary parameters d and f in chain trace generation

nix/.stack.nix/delegation.nix, shelley/chain-and-ledger/cddl-spec/shelley.cddl, shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/src/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/MetaData.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/Shrinkers.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/transactions.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This PR introduces transaction metadata to the shelley ledger.
The metadata type itself was mostly taken from the plutus repo:  https://github.com/input-output-hk/plutus/blob/master/plutus-tx/src/Language/PlutusTx/Data.hs
We will not supporting the `Constr Integer [Data]` constructor for the first release of Shelley, though. In Shelley we call the `Data` type `MetaDatum`. And there is a `MetaData` type for a mapping of `Word64` to `MetaDatum`. Please let me know if there are better names.
The transaction body now contains an optional field for the hash of metadata.  The transaction itself now contains a new third component, optional metadata. The `UTXOW` STS rule now requires that: either both the metadata hash and the metadata are absent, or the hash of the later is equal to the former. …
=> new feature - transaction metadata

shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ocert.hs, shelley/chain-and-ledger/executable-spec/test/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
This extends the generator for blocks with evolving KES keys, newly registered hot keys and fixes generators for certificates. For these generators we could be generating invalid certificates in the case of waiting IR or retiring pools.
=> Generator to evolve KES keys, register new hot keys, fix some generators

shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex
This PR adds support for block numbers in the block header. It was previously included in the exec spec, as a part of the block header body, though it was not used by the ledger. We now include the block numbers in the formal spec and use it for a new check.
In particular:
* the `BlockNo` value is now apart of the state for the `PRTCL` and `CHAIN` transitions. This represents the last seen block number.
* `PRTCL` now checks that the block header being processed is exactly one greater than the last block number.
I added a TODO to the formal spec for figuring out how to get the last block number from the byron chain state. (See Figure 82, "Byron to Shelley State Transition".)
=> Block Number checks

shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/formal-spec/delegation.tex
This activates block generation in the tests for Praos slots. The essential
change is to filter the pool distributions for non-emptiness, else we allowed
block creation for pools without delegated stake.
cf. #1198
=> Generate blocks in Praos slots

shelley/chain-and-ledger/formal-spec/properties.tex
We recently fixed a problem with the instantaneous rewards mechanism.  See #1191.  This PR updates the preservation of ada proof in the properties section. (And fixes a few typos the auditors found.)
=> fix preservation of ada proof

shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
This turned out to be unnecessary and added unneeded complexity.
=> Revert change to add explicit pool keys in generators

shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
When generating blocks in CHAIN, we are now using the ledger state produced by
TICK which includes the changes we had added as constraints for the generators.
This includes picking withdrawals, pools to delegate to and credential
de-registration.
=> Simplify generators by removing some contraints

shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
When the protocol parameters are changed, the new ones have to be used to
generate the transactions for LEDGERS.
There can also be a change to the reserves in TICK, so we also used the
potentially new value to pass it on to the signal generator of LEDGERS.
Closes #1211
=> Pass TICK changes in pParams and account state to LEDGER siggen

shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs, shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
Closes #1215 
This PR also removes all dummy HasTrace instances for Shelley STS's (these instances are redundant since we only have LEDGER/LEDGERS/CHAIN traces)
=> [1215] Classify Epoch Boundaries in Chain traces

shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
This introduces a simple fee calculation for the generated transactions.
Effectively we use the original transaction, then-recalculate the fees and update the Tx fees and pay the fees from the generated TxOuts.
If the fees cannot be covered we discard the Tx.
resolve #876
=> Simple fee calculation

shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
Before, we generated at most 5 initial UTxO entries and created at most 2
outputs in a transaction which consumed betweed 1 and 5 inputs. Therefore the
size of the UTxO quickly converged to 1-2.
This commit changed this to generate between 10 and 100 initial UTxO entries and
then using somewhere between 1 and 10 as inputs. The number of receipients is
generated using then number of inputs, contracting by 1 or expanding by one with
a relative frequency of 1 and generating the same number of outputs as consumed
inputs, with a relative frequency of 2.
=> Generate larger UTxO for more variance

shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs
small fix to the `AVUP` transition, fixing the test `CHAIN example 4B - create a future app version`.
=> fix AVUP STS rule

shelley/chain-and-ledger/cddl-spec/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/PParams.hs, shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs, shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/formal-spec/update.tex
This PR does two main things:
* the protocol version is now a pair of numbers instead of a triple. The rules for increasing the protocol version now simplify to `(m,n) -> (m,n+1)` or `(m,n) -> (m+1, n)`
* inside of application version updates, the `ApName` and `SystemTag` types are now restricted to UTF8 (instead of ascii) and 64 bytes instead of 10 and 12.  I think it no longer makes much sense to enforce the sizes in the formal spec, but in the types and the serialization. I have removed the restrictions from the pdf, and in the exec model we now replace the constructors with functions that do not allow more than 64 bytes, and the FromCBOR instances no longer allow for deserializing more than 64 bytes.
closes #1148
=> protocol version as two naturals

shelley/chain-and-ledger/executable-spec/delegation.cabal, shelley/chain-and-ledger/executable-spec/test/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Generator/DCertTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
Closes #868 
* introduces a custom CERTS STS that thinly wraps the DELPL STS and adds a HasTrace instance (the Env and State of CERTS is constrained by the context available in genTx from which we generate certs)
* replaces `genDCerts` with a new one based on the CERTS Trace
* change `genRegKeyCert` to return _no witness_ (was returning a superfluous witness that needed special handling at a few sites)
* reduce `numBaseScripts` from 5 to 3 until we solve the test perf issues
* add a trace classification for multiple certs per transaction and also recalibrates the classifier now that we have more certs being produced
* increase lower bound on block size from 30k -> 50k (our generated blocks have been getting bigger)
* incorporate transaction IX in LEDGERS generation of `Seq Tx`
=> [868] Generate multiple certs per tx

shelley/design-spec/CHANGELOG.md, shelley/design-spec/delegation_design_spec.tex
Adding a factor of (active stake)/(total stake) to the monetary expansion, to prevent an incentive to censor new stake key registration or delegation certificates.
=> Clarify when to use total/active stake.

nix/haskell.nix, release.nix, shelley/chain-and-ledger/dependencies/non-integer/test/Spec.hs, shelley/chain-and-ledger/executable-spec/src/PParams.hs, shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Tests.hs
Failing test:
```
Invalid signals are generated when requested:       FAIL
Exception: Prelude.undefined
CallStack (from HasCallStack):
error, called at libraries/base/GHC/Err.hs:78:14 in base:GHC.Err
undefined, called at src/Ledger/Delegation/Test.hs:27:22 in cs-ledger-0.1.0.0-IT195XGeNtxHozoOHTCQsV:Ledger.Delegation.Test
coverDelegFailures, called at test/Ledger/Delegation/Properties.hs:427:8 in main:Ledger.Delegation.Properties
```
(`nix-build -A checks.tests.cs-ledger.ledger-rules-test`)
=> Require tests checks to pass on hydra

shelley/chain-and-ledger/cddl-spec/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Mutator.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/UnitTests.hs, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex
This PR adds optional pool metadata (a url and a hash) to the registered stake pool parameters, as per section 3.4.4 and 4.2 of the Delegation Design document. This is the third 64 byte UTF-8 type I've added, so I tried to reduce code duplication by adding a new `Text64` type to the base types module.
It also adds the list of pool relays to the registered stake pool parameters, which is an upcoming change to the delegation design doc.
closes #1132
=> optional pool metadata and pool relays in pool params

shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs
Mirco PR! This adds two more "preservation of ADA" unit tests. probably not necessary since we have property tests for this, but it was easy to add :)
=> adding in two more preservation of ada unit tests

shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/update.tex
This PR adds a mechanism for halting outdated nodes.
There is a new constant, `MaxPV`, a protocol version, and a new predicate in the `CHAIN` rule that checks that the current protocol version is less than or equal to `MaxPV`.
The constant appears in the executable model as a new field in `Globals`.
Additionally, I discovered that the the formal spec wasn't updated everywhere it should have been in #1238, and so I've done that in this PR.
closes #1149
=> mechanism to halt obsolete nodes

shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/STS/Rupd.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
This PR corresponds to the changes described in #1243 
The reward calculation now computes relative stake based on total stake instead of active stake.
I made total stake a new global parameter, `maxLovelaceSupply`.
Using total stake instead of active stake made the reward calculations in the examples trivial: since the active stake was so small compared to 45B ADA, the rewards were zero. So I gave more stake to the initial genesis UTxO, and used this opportunity to make the example less brittle.
closes #1244
=> using total (not active) stake for reward calc

shelley/chain-and-ledger/cddl-spec/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/Serialization.hs, shelley/chain-and-ledger/executable-spec/src/Tx.hs, shelley/chain-and-ledger/executable-spec/src/TxData.hs, shelley/chain-and-ledger/executable-spec/src/UTxO.hs, shelley/chain-and-ledger/executable-spec/src/Updates.hs, shelley/chain-and-ledger/executable-spec/test/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Rules/TestUtxow.hs, shelley/chain-and-ledger/executable-spec/test/Test/CDDL.hs, shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
When the ruby script returns standard error, the CDDL tests now report a failure. A few tests needed fixing on the Haskell side. The full transactions `Tx` now pass, but there are still some problems with the full block, so those tests are commented out. The tests now pass for me locally, but we still do not have them working in CI.
The remain test fixes will be done in #1270
closes #1253
=> report std error in shelley CDDL tests, fix tests

shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
Micro PR! :microscope:  Just removing a comment about the previous header hash inside the Shelley block header. See #1266
=> removing prev hash todo

byron/ledger/formal-spec/blockchain-interface.tex
Per Damian's comment in the exec spec:
-- Note that we delete the registered application proposals from the
-- state on epoch change, since adopting these depends on the @cps@
-- and @pws@ sets, which are deleted as well. So it doesn't seem
-- sensible to keep @raus@ around
This brings the formal spec in line with the exec spec and the implementation.
=> Zero 'raus' on epoch change/

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Keys.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/PParams.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs
handle the edge cases in the active slot coefficient optimizations for the VRF leader check.
closes #1271
=> active slot coefficient optimization edge cases

byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/formal-spec/default.nix, byron/ledger/formal-spec/update-mechanism.tex
Addresses part of https://github.com/input-output-hk/cardano-ledger/issues/739 by disallowing (rather than coaelescing) duplicate votes.
It is now an error to include a vote in a block which has already been included in the vote tally. The mempool should therefore reject it.
There will be a corresponding change to `cardano-ledger` updating this in the implementation.
=> Prevent replay attacks using votes

shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Fees.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs
A handful of examples of various transactions together with their abstract size. Note that the minimum fee is just `ax+b`, where `x` is the abstract size and `a, b` are protocol parameters.
closes #1286
=> fee examples

shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/OCert.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Bbody.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ocert.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/formal-spec/chain.tex
The operator verification key was redundantly being stored in both the block header and the operational certificate. now it's not.
closes #1290
=> removing redundant vkey from block

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
This PR aligns the pool parameters for a given reward calculation with the corresponding stake pool distribution instead of the corresponding performance period (performance is always based upon the previous distribution).
In detail, this means removing `_poolsSS` from the `Snapshots` record and adding this parameter mapping to each individual snapshot. Since each snapshot now has three things (stake distribution, delegation mapping, and pool parameters), I've turned the snapshot into its own type.
closes #1297
=> aligning pool params with stake distribution

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/formal-spec/update.tex
This PR restricts the protocol parameter update window by another "2k" slots, this giving us an entire stability period between when we know that the protocol version is changing and the end of the epoch.
This addresses the shelley concerns regarding #1288
=> reducing proto param update voting period

shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Address.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Scripts.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Tx.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Fees.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Shrinkers.hs
New module `Shelley.Spec.Ledger.Scripts` added. Much of the MultiSig stuff (except for the evaluation function) moved to it. This is in preparation for Goguen, so that it is possible to have Plutus script - related things in this module as well.
=> Script stuff moved to Scripts

byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Epoch.hs, byron/chain/formal-spec/blockchain-spec.tex, byron/chain/formal-spec/default.nix, byron/ledger/executable-spec/src/Ledger/GlobalParams.hs, byron/ledger/executable-spec/src/Ledger/Update.hs, byron/ledger/formal-spec/blockchain-interface.tex
This addresses both #1288 and https://github.com/input-output-hk/cardano-ledger/issues/743
Endorsements are now counted up until 4k slots from the start of the epoch, not 2k from the first block in the epoch.
=> Change how endorsements are counted

shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl, shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/CDDL.hs
The CDDL test now test that the serializations validate against the CCDL spec.
The tests do now take a lot longer, so we reduced the number of trials. We can run a lot more once we get the nightly tests running.
closes #1254
=> testing serialization against the CDDL file

shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Rewards.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Mir.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs
EDIT: I've drastically redone this PR.
Reward updates now include a new component, `nonMyopic`, which stores the info needed to compute the non-mypopic rewards:
* the mapping of moving averages apparent performances
* the reward pot
* the snapshot used to create the reward update (the one marked "go").
I've created a new module, `Shelley.Spec.Ledger.Reward`. I moved the reward calculations to this module, and implemented all the non-myopic reward calculations in it.
There are still some TODOs relating to questions for the researchers. The spec still needs to be updated, and the `Cardano.Shelley.API` module and helper functions still need to be written.
see #1236
=> stake pool desirability ranking

cabal.project, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Mir.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Newpp.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs, stack.yaml
This commit removes the following `Failure*` constructors that do not occur outside of their own definition.
```
$ git grep -e ' Failure' 5d7e2705 -- 'shelley/*hs'
5d7e2705:shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Newpp.hs:    = FailureNEWPP
5d7e2705:shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs:    = FailurePOOLREAP
5d7e2705:shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs:    = FailureRUPD
5d7e2705:shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Snap.hs:    = FailureSNAP
5d7e2705:shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs:  data PredicateFailure (UPDN crypto) = FailureUPDN
$ git grep -e FailureNEWPP -e FailurePOOLREAP -e FailureRUPD -e …
```
=> Remove unused PredicateFailure constructors

shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal, shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API.hs, shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API/Wallet.hs
makes an API for the non-myopic member rewards.
closes #1236 
(I made #1319 for updating the formal spec)
=> nonmyopic rewards api

cabal.project, shelley/chain-and-ledger/executable-spec/test/Setup.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/shelley-spec-ledger-test.cabal, stack.yaml
Similarly to how `cardano-ledger` exposes its test suite as the `cardano-ledger-test` package, this commit exposes the generators and examples (but not the tests themselves) from the testsuite of `shelley-spec-ledger` as the `shelley-spec-ledger-test` package.
This makes it possible for consensus to reuse the existing generators and examples for testing the Shelley ledger integration instead of having to write them from scratch.
=> Expose the shelley-spec-ledger test helpers as a package

shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/Chain.hs
The Shelley ledger can now start from origin or from Byron, and should integrate better with the consensus layer.  The previous hash is now essentially a maybe type, and the chain state now stores the last slot, block number, and prev hash only if they exist.
Here are a couple potentially interesting subtleties:
* The VRF check takes as an input (among other things) the previous header hash. We could provide some arbitrary value for the genesis block, but the check itself doesn't really make sense in this case. Instead, I've just skipped the VRF checks for the first block. Note that that the VRF checks would not even happen on the first block if the decentralization parameter was set to 1.
* As a part of the evolution of the epoch nonce, we add the previous hash of the last block of the …
=> Allow Shelley ledger to start at origin

shell.nix
I needed to add this line in order to use `cabal` commands from inside the `nix-shell`. That's my typical local workflow; I don't know if the owner's of this repo want to support it. If so, this PR might suffice... For Your Consideration :)
=> Add cabal-install to shell.nix

shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs
Apparently ouroboros-network's CI builds its dependencies with Haddock enabled. The PR for the Shelley integration is giving Haddock parse errors, see: https://hydra.iohk.io/build/2092683/nixlog/3. So we need to fix them before we can merge that PR.
=> Fix Haddock parse errors

byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs
We're reusing this generator in ouroboros-consensus and the debug trace is making our test output unreadable.
=> Remove left-over debug trace

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Coin.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PreSTSMutator.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PropertyTests.hs
The `mutateCoin` function would sometimes subtract one from a coin value, which gives a negative values when passed zero. This mutator now uses the natural number mutators instead.
I also changed how `Coin` is serialized. It will become a cbor integer if it holds a negative value, and a uint otherwise. The idea is that this will provide clear errors, and will fail to validate against the cddl spec. For derserialization, we return a `DecoderError` for negative values.
closes #1341
=> do not generate negative transaction tx outs

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/formal-spec/chain.tex
This PR makes the corresponding changes to the formal spec that #1317 made to the exec model , namely allowing Shelley to start from genesis or Byron.
Instead of introducing two new optional types (as was done in the haskell code: `PrevHash` and `WithOrigin`), I just reused the optional type already present in spec.
While updating the spec, I found a mistake in the `mkSeed` function. It was taking the epoch nonce, the slot, and the previous header hash to produce the seed for the VRF check. But the `UPDN` rule already combines the epoch nonce candidate with the previous header hash, so `mkSeed` only needs the epoch nonce and the slot.
closes #1327
=> formal spec can now start from genesis or from byron

shelley/chain-and-ledger/formal-spec/chain.tex
The `h_c` and `b` names didn't match the corresponding figure(s) (`ph` and `ne`, respectively).
I looked at the surroundings and judged that `h_c` and `b` were stale.
I tried to find all uses, but I'm not sure I got them all -- please double-check.
=> fix up stale variable occurrences

shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/properties.tex
I'm guessing the TICK environment used to contain a nonce and its occurrence in that particular explanation was overlooked when it was removed.
The star vs seedOp patch is invisible in the rendered PDF but caused me a tiny bit of confusion when I was trying to track down the definition of that operator symbol (since I could not copy-and-paste the symbol into the CTRL-F dialog).
=> fix a couple typos

shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PropertyTests.hs, shelley/chain-and-ledger/formal-spec/epoch.tex
The full set of properties are run as part of nightly's with some properties currently failing (due to a bug present when generating multiple certificates per transaction). 
This PR 
* reverts to generating only one cert per transaction - this should get us passing nightly test runs - see  #1352 
* stubs out the removedAfterPoolReap failing property - see #1351 
* fixed a few typos in the spec
=> Revert to generating transactions with up to one certificate

nix/sources.json, shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Presets.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/Chain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/DCert.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/Ledger.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestChain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestLedger.hs, shelley/chain-and-ledger/executable-spec/test/shelley-spec-ledger-test.cabal
The various trace tests were using fixed sets of keys, referenced in various places. This made it pretty difficult to use outside of the standard test generators.
This PR unifies the various keys needed during trace generation into a `KeySpace`, which is passed in from the top of the tests.
=> Rewrite tests to not use fixed key sets

byron/cddl-spec/default.nix, semantics/formal-spec/default.nix, shelley/chain-and-ledger/dependencies/non-integer/doc/default.nix, shelley/chain-and-ledger/formal-spec/default.nix, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/design-spec/default.nix
There are at least two taus in the Praos paper: one is a parameter of the Chain
Growth property and the other is a parameter of the Resettable Leaky Beacon
Functionality. The SlotsPrior global constant refers to the RLB Functionality
parameter.
@JaredCorduan @uroboros, it is the RLB tau, right? Thanks!
=> clarify which tau in Praos reference

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Validation.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/properties.tex
This PR adds the header-only validation properties to the Shelley ledger spec. They are nearly identical to the Byron versions. The biggest difference is that the environment and states are the same for the main `CHAIN` rule and the corresponding header-only version (unlike Byron).
Because the `CHAIN` rule is a bit messier than the corresponding one in Byron, I thought it made sense to actually spit it up into a header-only piece and the body piece in the main rules, instead of just defining a new rule in the section on the properties. The header-only part is called `CHAINHEAD`. My hope is that the consensus layer could actually call this transition.
If this division makes sense, I will clean up the prose and adapt the executable model (ie add `CHAINHEAD`.
So, `CHAINHEAD` and `CHAIN` look …
=> Adding the header only validation properties to the formal spec

shell.nix, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Constants.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Delegation.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Presets.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/Chain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/DCert.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/Ledger.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Update.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestChain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestLedger.hs
Second step of abstracting over things in the tests. We now pull out the various constants which guide test generation. Needed for integration into ouroboros-consensus testing.
=> Abstract over constants.

README.md, shelley/chain-and-ledger/formal-spec/chain.tex
Micro PR :microscope: 
1) Unpack the `nes` variable in the `NEWEPOCH` rules
1) Remove the broken standalone multi-sig document link from the README. The document still builds, but it has been incorporated into the main spec and is no longer being built in hydra. The document can still be built, however (I waffled on whether or not to delete it...).
=> Formal Spec - unpack NES state in NEWEPOCH rules

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Address.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/EpochBoundary.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PreSTSGenerator.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Utils.hs
Addresses are now either a pair of a payment credential and a stake reference (which can be null), or a bootstrap address.
Note that the serialization is the same, we will overhaul the binary format soon.
closes #1364
=> better address types for symmetry

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Keys.hs
- The `NFData` instances are required for work being done as part of https://github.com/input-output-hk/cardano-node/pull/799.
- The patterns `VKey` and `VKeyGenesis` are exported as data constructors of the type `DiscVKey` in order to prevent modules that import these symbols from being forced to enable `PatternSynonyms`.
i.e., you can do:
```import Shelley.Spec.Ledger.Keys (DiscVKey(VKey, VKeyGenesis))```
instead of:
```import Shelley.Spec.Ledger.Keys (pattern VKey, pattern VKeyGenesis)```
- The `COMPLETE` pragma to indicate that the set of patterns `VKey` and `VKeyGenesis` are complete, therefore preventing non-exhaustive pattern match warnings.
=> Derive NFData instances and export VKey and VKeyGenesis patterns as data constructors

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Validation.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Mir.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/NewEpoch.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Newpp.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ocert.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Tick.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs
We need access to the constructors of all the failures so that we can render them as errors in the log files.
The `PredicateFailure` for some STS rules have no constructors of course but for uniformity we just export them from every module.
=> Export PredicateFailure from all STS modules

shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Shrinkers.hs
This didn't produce a warning in this project but did when used in
'cardano-node'.
=> test: Add a RankNTypes pragma

shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Delegation.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/DCert.hs
The generators previously assumed that the public key for a stake pool
was a _staking key_. But this is somewhat strange - it's neither a
payment key nor a staking key, it's in a completely different domain. In
the shelley testing, we would like these to correspond to the genesis
key delegate, so they can issue blocks either under Praos or the
Overlay.
This PR just looks them up in the wider set of key hashes, which
includes the staking keys anyway.
=> Use all key hashes for stake pool retire certs.

shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/PParams.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Update.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Utils.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
closes #1386 
Note that there is no longer a collection of protocol parameters in the environment of the `OVERLAY` transition.
=> Make the active slot coeff a constant (not a protocol parameter)

shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Presets.hs
Useful for testing in the 'node' repo.
=> shelley-spec-ledger-test: Expose coreNodeKeys function

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Tick.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/TestScenario.hs, shelley/chain-and-ledger/executable-spec/test/Tests.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger.tex
Previously, new genesis key delegations were adopted in the base case of the `LEDGERS` transition.
This is unfortunate for the consensus integration, and would cause the header validation properties to fail. This PR moves this update to the `TICK` transition.
=> Adopt genesis delegations in the TICK rule

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs
=> fix overlay schedule bug with no genesis nodes

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Protocol.hs
We used to call the NEWEPOCH rule, but this was done with the
understanding that TICK changes related to the ledger view all happened
on the epoch boundary. This was true, but only because genesis
delegations took place inside the ledger rules, rather that in TICK.
This is problematic (it violates future time travel implementation), so
now genesis delegation updates happen in TICK and we call that.
Also, we used to not be able to call TICK because it was called BHEAD
and took the header. Now we can, so just calling it is easier!
=> Call the 'TICK' rule in future ledger view.

semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PropertyTests.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/ClassifyTraces.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestChain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestNewEpoch.hs
Closes #1351 
Closes #1392 
* re-introduces the removedAfterPoolReap prop which was failing when tested on CHAIN traces because these traces include the effects of LEDGER rules, which introduce new txs/certificates. These new certificates creates "noise" when testing for just the non-ledger effects of the POOLREAP rule
* switched from QC.forAllShrink to forAllShrinkBlind - this change solves the Heap Exhaustion we were getting when a property failed for a trace that was too large to Show
=> [1351] Re-enable the removedAfterPoolReap property

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Mempool.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Validation.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Bbody.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/UTxO.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Fees.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/MultiSigExamples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PreSTSGenerator.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PropertyTests.hs, shelley/chain-and-ledger/formal-spec/utxo.tex
The signatures are now of the transaction body _hashes_, not the transaction bodies.
closes #1417
=> sign transaction body hashes, not the body

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs
This function will be utilized by an additional Shelley local state query in `ouroboros-consensus-shelley` that returns the entire UTxO. This will probably be useful for quick demos, analysis, etc.
=> Add function to get the entire UTxO from the ShelleyState

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ppup.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Utils.hs, shelley/chain-and-ledger/formal-spec/Properties.md, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex, shelley/chain-and-ledger/formal-spec/notation.tex, shelley/chain-and-ledger/formal-spec/properties.tex, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/update.tex
* `slotsPrior` has been renamed `stabilityWindow` (which corresponds to `3k/f` in Praos)
* `startRewards` has been removed, and reward updates now start `stabilityWindow`-many slots into the epoch
* a new constant, `randomnessStabilisationWindow`, has been added, which is used only in the `UPDN` (update nonce) rule and which determines the point in the epoch when the evolving nonce stabilizes. this constant corresponds to `4k/f` in Ouroboros Genesis.
closes #1391
=> rename the stability window constants

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
Total stake (as opposed to _active stake_), which is used in the reward calculation, is now handled the same way as the delegation design document (section 5.5.1). In particular, it only includes lovelace which could potentially become active.
There is technically now no longer a need for the `MaxLovelaceSupply` global constant. I would be inclined to remove it, but I wasn't sure if it was a helpful convenience.
closes #1427
=> total stake should exclude certain buckets of ada

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
In #1428 the total stake valued used for the reward calculation was changed from the the max supply (ie 45B ada) to the sum of the ada held in base addresses, pointer addresses, and reward accounts. Unfortunately this turns out not to be what we want either. This PR reverts the early change and instead uses the max supply less the reserve amount.
The PR is easier to read if you ignore the revert and only look at the second commit. :)
=> total stake (for reward calculation) is max supply minus reserves

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Tx.hs
Consensus can use this annotation to compute the expected post-serialisation
size of the transaction.
=> Expose Tx.txFullBytes

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/PParams.hs
Explaining the use of the HKD type family in the `PParams'` docstring.
=> explain HKD in protocol parameters

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ocert.hs
The `InvalidKesSignatureOCERT` error now includes:
* The current KES period
* The start period in the OCert
* the difference between the the two above (current monus start)
=> InvalidKesSignatureOCERT now reports more

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Address.hs
`serialiseAddr` was completed with #1412
=> removing comments that serialiseAddr is unfinished

shelley/chain-and-ledger/executable-spec/cddl-files/mock/crypto.cddl, shelley/chain-and-ledger/executable-spec/test/Test/Cardano/Crypto/VRF/Fake.hs
We have tests in `ouroboros-network` that verify we can detect corruption. This was causing them to fail, since it didn't care about what was in the high bits of a `Word64`.
=> Make the encoding/decoding less lenient

README.md, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/PParams.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxo.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Update.hs, shelley/chain-and-ledger/formal-spec/protocol-parameters.tex, shelley/chain-and-ledger/formal-spec/utxo.tex
This PR represents a halfway move toward having UTxO deposits. In particular, it creates a new protocol parameter `minUTxOValue` and now checks that each new created transaction output is at least this value (therefore replacing the check that each output is non-negative).
I also took the opportunity to clean up the unit tests in `Test/Shelley.Spec.Ledger.Examples.UnitTests`. Several of them were redundant, less good version of tests now in `Test/Shelley.Spec.Ledger.Examples.Examples`, namely the `valid` ones. Others, the `invalid` ones, were using the `asStateTransition` function that pre-dates the `STS` framework, and I have now removed `asStateTransition` from these tests in favor of using the `LEDGER` rule directly.
I did not run ormolu (`scripts/ormolise.sh`). Or rather, I did run …
=> Minimal Value UTxO outputs

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Protocol.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Block.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Trace/Chain.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/shelley-spec-ledger-test.cabal
The PRTCL transition was doing block-specific checks:
* Hashes must align
* Slot number must increase
* Slot number must not be in the future (compared to wall clock slot)
* Block number must increase by one
These checks are *all* already done in consensus. Them being redundant is not
a problem, but in order to perform these checks, the PRTCL state stored
`LastAppliedBlock`. This coupled the *protocol* transition, which should be
independent/agnostic of the block, to the *block type* through its hash. One
could argue that this coupling should not be there.
The real problem is that when we hard fork from Byron to Shelley, we must be
able to translate the Byron protocol state to the Shelley protocol
state (called `ConsensusState` in consensus). At this point, we would have to
produce a …
=> Make PRTCL block-independent

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Protocol.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs, shelley/chain-and-ledger/formal-spec/chain.tex, shelley/chain-and-ledger/formal-spec/ledger-spec.tex
The PR updates the formal spec with the changes made in #1450.
Additionally, I found something that I missed while reviewing #1450, namely that the `PRTCL` state does not need the new `η_{ph}` nonce, this is redundant with `η_h`. We do, however, need to add `η_{ph}`  to the `PRTCL` environment so that `η_h` is updated.
=> Sync formal spec with exec model - make PRTCL block independent

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Validation.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Bbody.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledgers.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxow.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/NonTraceProperties/Generator.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/NonTraceProperties/Validity.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/STSTests.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/UnitTests.hs
This PR adds better errors for `InvalidWitnessesUTXOW` and `MissingVKeyWitnessesUTXOW`.
I hope to be able to add robust error types for **all** the ledger failures in the near future. But please let me know if there are certain failures that you would like me to prioritize.
closes #1456
=> some better UTXOW errors

shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Address.hs, shelley/chain-and-ledger/executable-spec/test/Tests.hs
Done : 
I run tests via : 
```
stack test shelley-spec-ledger:test:shelley-spec-ledger-test --ta '-p "golden tests"' 
```
=> Add realistic crypto golden tests for serialiseAddr

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxow.hs
This was caught by the roundtrip tests in consensus.
=> Fix off-by-one error in MissingVKeyWitnessesUTXOW decoder

shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BaseTypes.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Epoch.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ledger.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Pool.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Snap.hs, shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Rules/TestPool.hs, shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/STSTests.hs, shelley/chain-and-ledger/formal-spec/delegation.tex, shelley/chain-and-ledger/formal-spec/epoch.tex
**Edited with new plan**
In order to give delegators time to respond to stake pools changing their parameters, if I registered stake pool re-registers within the the last `StabilityWindow`-many slots in an epoch, the parameter updates are staged for adoption on the epoch boundary.
To handle this staging, a new mapping was added to `PState`, namely `fPoolParams`. These future pool parameters are adopted in the `Epoch` transition, right before the pool reap transition.
closes #1453
=> Pool Registration Certs not valid late in epoch
