input-output-hk/cardano-ledger-specs

- docs/delegation_design_spec/delegation_design_spec.tex
@dcoutts Thanks for the extensive review! This is the first batch of resulting changes :)
> Delegation design: changes after review (part 1)

- hs/package.yaml
- hs/src/Coin.hs
- hs/src/LedgerState.hs
- hs/src/UTxO.hs
- hs/test/Tests.hs
> Haskell generators for non-empty genesis state / advance to random valid ledger state

- hs/test/Generator.hs
- latex/properties.tex
this adds generators for 'DelegationData' for delegation transactions
> Generators for delegation model

- latex/epoch.tex
First draft, some todo's to discuss. 
Final Epoch boundary transition rule discussion still to come.
> Epoch Descriptions

- docs/delegation_design_spec/delegation_design_spec.tex
Moving to shorter PRs that are easier to review.
> Some updates/corrections to the delegation design

- latex/lhs2tex/LedgerSpec.lhs
- latex/lhs2tex/Makefile
- latex/lhs2tex/README.md
- latex/lhs2tex/iohk.sty
- latex/lhs2tex/shell.nix
Just for discussion. Small example of how lhs2TeX could
in principle be used to generate a PDF spec that can also be
typechecked (and possibly, to some extent, even executed)
from a single source.
> lhs2TeX spec demo

- lhs/.gitignore
- lhs/Makefile
- lhs/README.md
- lhs/Vending.lhs
- lhs/default.nix
- lhs/iohk.sty
I have taken @kosmikus 's lhs2tex example (inside `latex/lhs2tex`) and tried to adapt the inference rules to how I was imagining that they would be translated to Haskell.  There are build instructions inside `lhs/README.md`.
Included is a simple vending machine example that uses the small step semantics. Parts of the pdf still do not look great, but it should be close enough to get the idea.  Note that the tests can be run inside GHCi.
> experiment to try small step sem. with lhs2tex

- latex/delegation.tex
- latex/epoch.tex
- latex/intro.tex
- latex/iohk.sty
- latex/ledger-spec.tex
Descriptions to come later today. I will finish changing the Epoch boundary file to match these changes if the new rules make sense.
> Anytime rewards rules

- dependencies/semantics/hs/small-steps.cabal
- dependencies/semantics/hs/src/Control/State/Transition.hs
- hs/src/LedgerState.hs
This pulls in a local copy of the new version of `small-steps` and updates the `UTXO` rule.
> Update `UTXO` rule for new STS framwork

- hs/src/Delegation/Certificates.hs
- hs/src/LedgerState.hs
- hs/src/UTxO.hs
- hs/test/Generator.hs
- hs/test/Mutator.hs
- hs/test/UnitTests.hs
This PR adds support for withdrawing rewards in the transactions.
Since I had to change the witnessing check anyway, I also added:
- checking certificate signatures
- rejecting transactions with redundant signatures
closes #88
> adding reward withdrawals

- hs/src/LedgerState.hs
- hs/test/UnitTests.hs
> Transactions update fees and deposits in UTxOState

- hs/test/Generator.hs
- hs/test/PropertyTests.hs
> Property-based tests after witness checking

- latex/delegation.tex
- latex/epoch.tex
- latex/ledger-spec.tex
> Witnesses cleaned up

- hs/src/LedgerState.hs
LEDGER -> UTXOW -> UTXO
Correctly type signals and environment for transition rules, delegation is not touched atm.
> Implement `UTXO` part of rule hierarchy

- latex/delegation.tex
- latex/frontmatter.tex
- latex/ledger-spec.tex
very quick PR to add some page breaks. it is not perfect, but this should help readability a lot. I've also added a version (`0.9`) and added "IOHK Formal Methods Team" as the author.
> adding version, IOHK team author, and page breaks

- hs/src/LedgerState.hs
The method names `created` and `destroyed` were backwards. We recently swapped the names is the latex, now we are swapping them in the Haskell model.
> Swapping the names created and destroyed

- hs/src/LedgerState.hs
- hs/test/UnitTests.hs
refactor `correctWithdrawals` and add STS framework rule for `DELRWDS`
> STS rule `DELRWDS`

- docs/delegation_design_spec/delegation_design_spec.tex
- docs/delegation_design_spec/references.bib
The last batch of changes in reply to Duncan's extensive review 😅
> Further changes to delegation design doc

- docs/delegation_design_spec/delegation_design_spec.tex
I changed three things:
- The handover phase as detailed implicitly assumed a public leader schedule. I've moved away from that.
- I've removed a TODO that is not necessary.
- I've bumped the version number to 1.0 😄
> Delegation design doc V1.0

- hs/src/LedgerState.hs
Adds remaining STS rule definitions to implement all `LEDGER` rules.
> Finish STS rule implementations for `LEDGER`

- latex/delegation.tex
- latex/epoch.tex
- latex/ledger-spec.tex
This adds the stake distribution calculation to the latex spec. #118
> stake distribution calculation

- latex/delegation.tex
- latex/epoch.tex
- latex/frontmatter.tex
Adding the reward calculation to the spec.
> reward calculation

- .gitignore
- docs/delegation_design_spec/Makefile
- docs/delegation_design_spec/delegation_design_spec.tex
- latex/Makefile
- latex/frontmatter.tex
- latex/gitinfo2.mk
- latex/ledger-spec.tex
With the rapid iterations of our documents, I find the git reference in the title matter helpful.
> Include git revision in documents

- hs/src/LedgerState.hs
- hs/test/Generator.hs
- hs/test/PropertyTests.hs
- hs/test/UnitTests.hs
Add `ptrs` to ledger state and extend ledger state with information about the current slot, keep track of transaction indices in ledger state.
> Add `Ptr` type to `LedgerState`

- .gitignore
- latex/Makefile
- latex/default.nix
allows to be built by hydra later to autogenerate artifacts
> latex build scripts

- hs/src/Delegation/Certificates.hs
- hs/src/EpochBoundary.hs
- hs/src/LedgerState.hs
- hs/src/PParams.hs
- hs/src/UTxO.hs
- hs/test/Generator.hs
- hs/test/UnitTests.hs
Apply this change in the executable spec, too.
> Rename `PrtclConsts` to `PParams`

- hs/src/Delegation/Certificates.hs
- hs/src/EpochBoundary.hs
- hs/src/PParams.hs
- hs/test/Generator.hs
- hs/test/UnitTests.hs
- `UnitInterval` for parameters in [0,1]
- `StakeShare` for stake distribution
depends on #169
> Add types for unit intervals

- hs/src/Delegation/Certificates.hs
- hs/src/Delegation/StakePool.hs
- hs/src/EpochBoundary.hs
- hs/src/PParams.hs
- hs/test/Generator.hs
- hs/test/Mutator.hs
- hs/test/UnitTests.hs
- latex/epoch.tex
> Add reward splitting functions

- hs/src/EpochBoundary.hs
- hs/src/LedgerState.hs
- hs/src/Slot.hs
- latex/epoch.tex
> Add functions for reward calculation

- hs/src/LedgerState.hs
> Use `Avgs` instead of `Distr`, relax contraints to non-negative

- latex/appendix.tex
- latex/epoch.tex
- latex/ledger-spec.tex
- latex/properties.tex
- latex/references.bib
uses TPTP format and the MetiTatrski prover: https://www.cl.cam.ac.uk/~lp15/papers/Arith/index.html
formalizations and proofs are added to appendix, proofs are hidden by default
> Some formalized proofs for numerical properties

- hs/src/Delegation/Certificates.hs
- hs/src/LedgerState.hs
- hs/src/PParams.hs
- hs/src/Slot.hs
- hs/src/UTxO.hs
- hs/test/Generator.hs
- hs/test/PropertyTests.hs
- hs/test/UnitTests.hs
- latex/ledger-spec.tex
Update for remaining STS rules to comply to the spec. Some small changes in latex docs.
> Converge model and executable spec

- latex/CHANGELOG.md
This PR adds a changelog. What is currently in `Unreleased` will soon be turned into a version `1.2` section. #228 
Please let me know if you like the format and any ideas you have about how we can make it better!
> adding a changelog

- README.md
> Add: Documentation for nix-build process.

- dependencies/non-integer/app/Main.hs
- dependencies/non-integer/reference/non_integral.c
- dependencies/non-integer/reference/non_integral.h
- dependencies/non-integer/reference/non_integral.hpp
- dependencies/non-integer/reference/non_integral_test.cpp
- dependencies/non-integer/reference/randomize.cpp
- C reference implementation based on GMP
- C++ example program
- random test generator
- test program in Haskell / C++ for result comparison
passed 1000000 random tests for `x^y` with `x, y \in [0.1, 1.9]` using 34 decimal digits precision, 10e-24 epsilon for approximation and 17 decimal digits comparison
> Reference implementation of non-integer calculations

- specs/ledger/latex/utxo.tex
…allowed by the protocol parameters.
Closes https://github.com/input-output-hk/cardano-chain/issues/135
> Check that the transaction size does not exceed the maximum size

- latex/delegation.tex
> Fixes small typo

- specs/ledger/latex/delegation.tex
> Restrict the delegation epoch to the current or next epoch.

- README.md
- default.nix
- dependencies/non-integer/doc/Makefile
- dependencies/non-integer/doc/default.nix
- latex/Makefile
- release.nix
- specs/ledger/latex/Makefile
> Add links in the README to the PDF's produced by hydra

- hs/src/Coin.hs
- hs/src/LedgerState.hs
- hs/src/PParams.hs
- hs/src/UTxO.hs
- hs/test/Generator.hs
- hs/test/Mutator.hs
- hs/test/PropertyTests.hs
This reflects the choice of Z for coin values in the spec.
> Use `Integer` for `Coin` values instead of `Natural`

- specs/ledger/latex/update-mechanism.tex
Also.
- Remove dead link to `wallet-new/docs/updates.md`
- Pin `docs/block-processing/us.md` to the latest commit.
> Specify that `upropTTL` is.

- hs/src/Delegation/Certificates.hs
- hs/src/Delegation/PoolParams.hs
- hs/src/EpochBoundary.hs
- hs/src/LedgerState.hs
- hs/src/STS/Epoch.hs
- hs/src/STS/Ledger.hs
- hs/src/STS/Newpp.hs
- hs/src/STS/PoolReap.hs
- hs/src/STS/Snap.hs
- hs/src/STS/Utxo.hs
- hs/src/UTxO.hs
- hs/test/Generator.hs
- hs/test/PropertyTests.hs
- hs/test/UnitTests.hs
This change came as a result if comments from the auditors.
> Use Data.Map.Strict instead of Data.Map

- shelley/chain-and-ledger/formal-spec/address.tex
- shelley/chain-and-ledger/formal-spec/appendix.tex
- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/crypto-primitives.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/epoch.tex
- shelley/chain-and-ledger/formal-spec/frontmatter.tex
- shelley/chain-and-ledger/formal-spec/intro.tex
- shelley/chain-and-ledger/formal-spec/ledger.tex
- shelley/chain-and-ledger/formal-spec/non-integral.tex
- shelley/chain-and-ledger/formal-spec/notation.tex
- shelley/chain-and-ledger/formal-spec/properties.tex
- shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
- shelley/chain-and-ledger/formal-spec/scripts-multicurrency.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
A first line-edit of the Shelley Spec (Formal Spec of the Cardano Ledger) - focussing on typos and grammar
> [#365] Basic edit

- shelley/chain-and-ledger/dependencies/non-integer/doc/Makefile
- shelley/chain-and-ledger/dependencies/non-integer/doc/non-integer-calculations.tex
- shelley/chain-and-ledger/dependencies/non-integer/reference/non_integral.c
- shelley/chain-and-ledger/dependencies/non-integer/reference/non_integral.h
- shelley/chain-and-ledger/dependencies/non-integer/reference/non_integral.hpp
- shelley/chain-and-ledger/dependencies/non-integer/reference/non_integral_test.cpp
- shelley/chain-and-ledger/dependencies/non-integer/reference/randomize.cpp
Use error estimation for Taylor series to short cut calculation if possible
> Optimize calculations for slot leader probability calculation

- shelley/design-spec/CHANGELOG.md
- shelley/design-spec/delegation_design_spec.tex
Also, given more thought about how this will work with Praos.
Also, giving the whole document an overhaul, pruning obsolete things, a couple of grammar edits, etc.
> Review of the design doc before initial publication.

- shelley/design-spec/delegation_design_spec.tex
I was a bit too slow for #380, so redid the suggestions here, together with the results of a run of langtool.
> Fix some typos / style changes

- shelley/chain-and-ledger/formal-spec/epoch.tex
The whole difference is now sent to the treasury.
> Fix prose to not mention unrealized rewards any more.

- shelley/chain-and-ledger/formal-spec/properties.tex
The ACCNT transition is obsolete.
> Remove accounting transition properties

- shelley/design-spec/Makefile
> Add synctex to the delegation spec document

- shelley/chain-and-ledger/dependencies/non-integer/doc/non-integer-calculations.tex
> Errata in natural logarithm Taylor expansion

- shelley/chain-and-ledger/dependencies/non-integer/doc/non-integer-calculations.tex
I hope this one is easier to merge!
> Missing parentheses in exp equation

- shelley/chain-and-ledger/dependencies/non-integer/test/Spec.hs
It's in the text displayed on the screen. Nothing serious!
> Errata in prop exp law description

- shelley/chain-and-ledger/dependencies/non-integer/test/Spec.hs
> Correct comment for `normalizeInts` function

- byron/ledger/executable-spec/src/Ledger/Update.hs
- byron/ledger/formal-spec/notation.tex
- byron/ledger/formal-spec/update-mechanism.tex
> Model application name and system tag checks

- weekly-reports/2019-05-31/milestone.org
> Complete two-week milestone for 31-05-2019

- shelley/chain-and-ledger/formal-spec/multi-sig.tex
- weekly-reports/2019-05-31/milestone.org
Add an alternative script-like multi-sig that could be implemented natively. Duncan provided an example implementation for this.
> [skip ci] Add Duncan's example implementation as alternative

- .buildkite/pipeline.yml
- ci/buildkite/default.nix
- ci/buildkite/rebuild.hs
- ci/buildkite/stack-hpc-coveralls.nix
- nix/stack-shell.nix
This job rebuilds the spec with stack, and uploads the coverage information to
coveralls.
> Add a "stack rebuild" job to the buildkite pipeline.

- README.md
Use the same style as the cardano-wallet and cardano-ledger-specs.
> Add buildkite, coveralls, and license badges, and remove travis badge.

- byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/SigCnt.hs
- byron/ledger/executable-spec/cs-ledger.cabal
- byron/ledger/executable-spec/src/Hedgehog/Gen/Aux.hs
- byron/ledger/executable-spec/src/Ledger/Core.hs
- byron/ledger/executable-spec/src/Ledger/Core/Generator.hs
- byron/ledger/executable-spec/src/Ledger/Delegation.hs
- byron/ledger/executable-spec/src/Ledger/Update.hs
- byron/ledger/executable-spec/src/Ledger/Update/Generator.hs
- byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs
- byron/ledger/executable-spec/test/Ledger/Pvbump/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
- byron/ledger/formal-spec/blockchain-interface.tex
- byron/ledger/formal-spec/properties.tex
- byron/semantics/executable-spec/src/Control/State/Transition.hs
- nix/.stack.nix/cs-ledger.nix
- release.nix
For the Byron-Shelley era, this patch formulates and implements three properties for the `PVBUMP` STS.
Closes #473.
> Formulates and implements properties for PVBUMP STS

- shelley/chain-and-ledger/formal-spec/multi-sig.tex
recently change to return `Bool` instead of `()`
> Update validation script return type

- byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/BHead.hs
> Remove `SIGCNT` from `BHEAD`

- byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Block.hs
Closes https://github.com/input-output-hk/cardano-ledger-specs/issues/479
> [479] Add size-costs for Block/BHeader/BBody

- byron/chain/formal-spec/blockchain-spec.tex
> Update the prose for the PBFT Header Processing

- byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs
- byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs
- byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOWS.hs
- byron/ledger/executable-spec/src/Ledger/Delegation.hs
- byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs
This should allow us to define the 'money is constant' property for the whole CHAIN system, which is nice :)
> Add UTxO payload to the CHAIN HasTrace instance

- byron/ledger/executable-spec/src/Ledger/Update.hs
This PR adds initial rules to the UPIREG, UPIVOTES and UPIEND STSes.
Closes #548.
> Specifies initial rules for UPI STSes

- byron/ledger/executable-spec/src/Ledger/UTxO/Generators.hs
It seems that the implementation of `subtractFees` which was added as part of PR #555 can generate `Tx`s which contain empty `outputs`. 
In `cardano-ledger`, `elaborateTxOuts` will panic if provided an empty list of abstract `TxOut`s since it needs to return a `NonEmpty Concrete.TxOut`. As a result, the `ts_prop_generatedChainsAreValidated` property will fail.
> Ensure `subtractFees` no longer generates `Tx`s with empty `outputs`

- byron/chain/formal-spec/blockchain-spec.tex
- byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXO.hs
- byron/ledger/formal-spec/properties.tex
- byron/ledger/formal-spec/utxo.tex
> Add properties about header/body validation split 

- byron/ledger/executable-spec/cs-ledger.cabal
- byron/ledger/executable-spec/test/Ledger/Relation/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
Closes https://github.com/input-output-hk/cardano-ledger-specs/issues/536
> [536] Property tests for Relation Instances

- byron/ledger/executable-spec/src/Ledger/Core.hs
- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/src/Keys.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Delpl.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ledger.hs
- shelley/chain-and-ledger/executable-spec/test/Mutator.hs
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/ledger.tex
Incorporates changes due to #565 #579
> Add future delegation mapping and adapt `DELEGS` STS rule

- README.md
- byron/ledger/executable-spec/src/Ledger/Core.hs
- byron/ledger/executable-spec/src/Ledger/Delegation.hs
- byron/ledger/executable-spec/test/Ledger/Delegation/Examples.hs
- byron/ledger/executable-spec/test/Ledger/Delegation/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
- byron/ledger/formal-spec/properties.tex
- Specify the property that delegation certificates cannot be replayed
- Test this property
Closes #511
> Test that delegation certificates cannot be replayed

- byron/chain/executable-spec/src/Cardano/Spec/Chain/STS/Rule/Chain.hs
- byron/chain/executable-spec/test/Cardano/Spec/Chain/STS/Properties.hs
- byron/ledger/executable-spec/src/Ledger/Update.hs
- byron/ledger/executable-spec/test/Ledger/Update/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
- byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs
- Add a signal generator for UPIEND
- Add a function `traceOfLength` to `HasTrace` to generate traces of certain length.
> Add UPIEND trace generators

- byron/ledger/executable-spec/src/Ledger/Core.hs
- byron/ledger/executable-spec/test/Ledger/Relation/Properties.hs
- byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
> [547] Add coverage testing for UTxO traces

- byron/chain/executable-spec/cs-blockchain.cabal
- byron/chain/executable-spec/test/Cardano/AbstractSize/Properties.hs
- byron/chain/executable-spec/test/Main.hs
- byron/ledger/executable-spec/cs-ledger.cabal
- byron/ledger/executable-spec/test/Ledger/AbstractSize/Properties.hs
- byron/ledger/executable-spec/test/Ledger/HasTypeReps/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
- nix/.stack.nix/cs-blockchain.nix
> [563] Test abstractSize for Block/Header/Body + UProp 

- LICENSE
- NOTICE
> Apache 2.0 license

- nix/.stack.nix/delegation.nix
- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/Keys.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Chain.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs
- shelley/chain-and-ledger/executable-spec/src/Slot.hs
- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/STSTests.hs
- shelley/chain-and-ledger/executable-spec/test/Tests.hs
This PR is my first step towards writing tests for the Shelly exec model with the STS framework.
In the spirit of small PRs, I wanted to merge these small additions needed to successfully apply the `CHAIN` transition in a unit test (along with two other simple STS unit tests).  I will replace the unit tests with property tests once we have the needed generators.
I've caught one small bug in the `epochFromSlot` function.
closes #637
> simple Shelley CHAIN STS test

- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/STSTests.hs
Adds several additional examples with different combinations of VKey and Multi-Sig witnesses
> Multiple Scripts, Scripts and Key Witnesses, Mutli-Sig Withdrawal examples 

- shelley/chain-and-ledger/formal-spec/epoch.tex
- shelley/chain-and-ledger/formal-spec/ledger.tex
- shelley/chain-and-ledger/formal-spec/non-integral.tex
- shelley/chain-and-ledger/formal-spec/properties.tex
Several typos addresses. (there was nothing to change for audit 9)
closes #663
closes #664
> Small edits from audit review #8 and #10

- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs
- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/update.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
give an explicit list of failure predicates for each STS rule, with the exception of wrapped failure predicates from sub-rules.
solves #605
> Explicitly list potential failure predicates for STS rules

- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs
- shelley/chain-and-ledger/executable-spec/test/STSTests.hs
Create separate module for Multi-sig examples
> Restructure multi-sig examples

- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Bbody.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ledgers.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Utxo.hs
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
- shelley/chain-and-ledger/executable-spec/src/UTxO.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Generator.hs
- shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
- shelley/chain-and-ledger/formal-spec/ledger.tex
- make `[Tx]` and `[DCert]` to `Data.Sequence` types
- fix sequence of predicate in `DELEGS`
- sub-rule sequence in `LEDGER`
> Fix problems in recursive STS rules

- shelley/chain-and-ledger/dependencies/non-integer/src/NonIntegral.hs
> Simplifications and fixes for non-integral calculations

- shelley/chain-and-ledger/formal-spec/update.tex
Two changes from the recent audit:
* removing name shadowing in one spot
* typo in removing outdated application version updates
> addressing audit from 2019 Aug 04

- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/epoch.tex
- shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
Fix the typos in the Shelley ledger formal spec which are listed in #749.
closes #749
> Issue #749 fix typos

- shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
Closes #735 
* use Union override in DELEGS STS (was using regular union before)
* used Relation operators where possible
* general re-styling 
@JaredCorduan I also tweaked the PPUP STS after your recent PR (If any of these stylistic changes don't work for you, I'll un-tweak!)
* there was another opportunity for using Relation `dom` in `(dom pup' ⊆ dom _dms) ?! NonGenesisUpdatePPUP (dom pup') (dom _dms)`
* removed "nested do" in `TRC (...) <- judgementContext`
* added some spacing
> [735] Sync executable with formal spec - DELEGS STS + Tweak PPUP STS

- .gitignore
- byron/semantics/executable-spec/small-steps.cabal
- byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs
- byron/semantics/executable-spec/src/Hedgehog/Extra/List.hs
- byron/semantics/executable-spec/src/Hedgehog/Extra/Manual.hs
> Better trace generators and more efficient shrink using edskos ideas

- shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
- shelley/chain-and-ledger/executable-spec/src/Updates.hs
Closes #733 
* sync DELEG STS (inline predicates + consequents, use Relation class, ...)
* use Relation class in AVUP STS (there were still some missed opportunities for Relation operators)
> Sync executable with formal spec - DELEG STS

- byron/chain/formal-spec/references.bib
> Update bib entry URL in blockchain-spec #790

- byron/ledger/executable-spec/src/Ledger/Core.hs
> Fix my non-convention-following changeset

- shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Snap.hs
Closes #737 
* make `aggregate+` more explicit in the exec spec
* use Relation operators more widely
> [737] SNAP STS - further align with formal spec

- shelley/chain-and-ledger/executable-spec/src/STS/Newpp.hs
> [738] NEWPP STS - in the exec. spec use firstSlot (as in formal spec)

- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/STS/NewEpoch.hs
> [741] NEWEPOCH STS - sync exec. spec with formal spec

- shelley/chain-and-ledger/executable-spec/src/STS/Bbody.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs
- shelley/chain-and-ledger/formal-spec/chain.tex
> [747] BBODY/OVERLAY STS - sync formal and exec. spec

- shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs
Closes #823 
(I came across this "out of sync" STS in preparing for the generator work, I think this PR simplifies the STS nicely, but it's arguable)
> [823] POOLREAP STS - further align with formal spec

- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs
- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestPoolreap.hs
- shelley/chain-and-ledger/formal-spec/properties.tex
Adapt and implement the property for `POOLREAP` that is in the formal spec for Shelley
> Property for `POOLREAP` rule

- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs
- shelley/chain-and-ledger/executable-spec/src/Keys.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Bbody.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Bhead.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ocert.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs
- shelley/chain-and-ledger/executable-spec/src/Tx.hs
- shelley/chain-and-ledger/executable-spec/src/Updates.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Generator.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
> remove Map.Map and Set.Set

- shelley/chain-and-ledger/formal-spec/address.tex
- shelley/chain-and-ledger/formal-spec/crypto-primitives.tex
- shelley/chain-and-ledger/formal-spec/ledger-spec.tex
- shelley/chain-and-ledger/formal-spec/transactions.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
> Shelley spec Review 15

- shelley/chain-and-ledger/formal-spec/Properties.md
This is a work in progress list of properties for the Shelley ledger. We can add it to the latex spec when it's ready.
closes #776
> handwritten properties

- byron/ledger/executable-spec/src/Ledger/Delegation.hs
> Check the signature of the delegation certificate in the `SDELEG` rule.

- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/properties.tex
- shelley/chain-and-ledger/formal-spec/transactions.tex
- shelley/chain-and-ledger/formal-spec/update.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
> some more corrections

- byron/ledger/executable-spec/cs-ledger.cabal
- byron/ledger/executable-spec/src/Ledger/Core.hs
- byron/semantics/executable-spec/small-steps.cabal
- byron/semantics/executable-spec/src/Data/AbstractSize.hs
- nix/.stack.nix/cardano-binary.nix
- nix/.stack.nix/cardano-crypto-class.nix
- nix/.stack.nix/cardano-prelude.nix
- nix/.stack.nix/cs-ledger.nix
- nix/.stack.nix/default.nix
- nix/.stack.nix/small-steps.nix
- nix/iohk-nix-src.json
- stack.yaml
Changes needed for https://github.com/input-output-hk/decentralized-software-updates/issues/30
> Add to cbor instances and HasTypeReps for ShortHash

- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/src/STS/Delegs.hs
- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestDelegs.hs
Adds a property-based test for `DELEGS` as described in the `Properties.md` file.
> Property test for `DELEGS`

- shelley/chain-and-ledger/executable-spec/src/STS/PoolReap.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestPoolreap.hs
properties that check that:
- deposits are always non-negative
- sum of circulation, fees, deposits, reserves, treasury and rewards is constant
> Add properties for `POOLREAP`

- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/epoch.tex
- shelley/chain-and-ledger/formal-spec/ledger-spec.tex
- shelley/chain-and-ledger/formal-spec/ledger.tex
- shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
First version of moving instantaneous rewards from the reserves to reward accounts.
> Move instantaneous rewards

- shelley/chain-and-ledger/formal-spec/non-integral.tex
> Remove checkmarks for exponentation in `poolReward` function

- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/epoch.tex
- shelley/chain-and-ledger/formal-spec/ledger.tex
- shelley/chain-and-ledger/formal-spec/update.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
> Consistently do not use parentheses for STS environments

- .gitignore
we don't want PDFs in the repo :)
> ignore PDFs

- shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/Coin.hs
- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs
- shelley/chain-and-ledger/executable-spec/src/Keys.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/OCert.hs
- shelley/chain-and-ledger/executable-spec/src/PParams.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs
- shelley/chain-and-ledger/executable-spec/src/Slot.hs
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
- shelley/chain-and-ledger/executable-spec/src/UTxO.hs
- shelley/chain-and-ledger/executable-spec/src/Updates.hs
Can be reviewed commit by commit; I may keep adding things to this branch, but also happy to merge earlier in order to avoid too much divergence.
> Things needed for integration with consensus

- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs
> [#869] Add DeRegKey generator & property

- byron/ledger/executable-spec/src/Ledger/Update.hs
Coverage before these changes:
Coverage with these changes:
Part of https://github.com/input-output-hk/cardano-ledger/issues/657
> Increase AlreadyProposedSv coverage

- byron/ledger/executable-spec/src/Ledger/Update.hs
> Check that the vote issuers are delegates of genesis keys.

- nix/iohk-nix-src.json
- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/test/Generator.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update.hs
Closes #867 
Replaces a fixture for `PParams` with generated values.
> [867] Generate PParams

- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/test/Generator.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo.hs
- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestPool.hs
> [#870] Generate `RegPool` DCerts

- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestPool.hs
Also creates a new test group for POOL and relocates the RegPool
property to it.
Closes #950.
> [#950] Add `pStateIsInternallyConsistent` property

- byron/ledger/executable-spec/test/Ledger/Core/Generators/Properties.hs
- byron/semantics/executable-spec/src/Control/State/Transition/Generator.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
> [925] Test that only valid signals are generated by LEDGER STS

- byron/ledger/executable-spec/src/Ledger/UTxO.hs
- byron/ledger/executable-spec/test/Ledger/UTxO/Properties.hs
- byron/ledger/executable-spec/test/Main.hs
- nix/iohk-nix-src.json
- release.nix
> Check property: utxo and transaction outputs (txouts) must be disjoint.

- shelley/chain-and-ledger/formal-spec/epoch.tex
cf. #972 
resolve #972 
buildkite doesn't seem to build from forks
> Typo: missing comma

- byron/ledger/formal-spec/Isabelle/Ledger_Rules_Formalization/Ledger_Rules.thy
- byron/ledger/formal-spec/Isabelle/Ledger_Rules_Formalization/ROOT
- byron/ledger/formal-spec/Isabelle/Ledger_Rules_Formalization/document/root.tex
This PR includes the proof of the UTxO constant money property.
> Add proof of UTxO constant money property

- shelley/chain-and-ledger/executable-spec/src/PParams.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/STSTests.hs
I squashed these commits before signing.
Contains implemented suggestions from #977.
Sorry for trouble, looks like I had a missing option in config.
> Commenting first example (really signed now)

- shelley/chain-and-ledger/formal-spec/incentives.tex
Small changes to deal with comments made by AS.
> Clean up Incentives Document

- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/UTxO.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
No longer require witness for stake credential registration.
closes #999
> No stake credential registration witnesses

- byron/semantics/executable-spec/small-steps.cabal
- byron/semantics/executable-spec/src/Control/State/Transition/Trace.hs
- byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs
- byron/semantics/executable-spec/test/Control/State/Transition/Examples/CommitReveal.hs
- byron/semantics/executable-spec/test/Control/State/Transition/Examples/Sum.hs
- byron/semantics/executable-spec/test/examples/Main.hs
- nix/.stack.nix/small-steps.nix
Add a `QuickCheck` `HasTrace` class, and associated functions.
> QuickCheck trace generators

- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Pool.hs
Remove the function `delegatedStake` which defined the partial function `addStake`
resolve #991
> Remove function that contains partial `addStake` function

- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/properties.tex
- shelley/chain-and-ledger/formal-spec/update.tex
- shelley/chain-and-ledger/formal-spec/utxo.tex
this PR replaces #1010 since buildkite cannot run on a fork PR.
cc @csoroz
> Fix errata: firstSlot misplaced parens (formal spec)

- nix/.stack.nix/delegation.nix
- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API.hs
- shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API/Mempool.hs
- shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API/Protocol.hs
- shelley/chain-and-ledger/executable-spec/src/Cardano/Ledger/Shelley/API/Validation.hs
This PR creates a top-level API for the consensus package (and any other interested clients) to access the Shelley ledger. The API is broken down into three pieces:
- Block validation and chain extension
- Mempool operations
- Protocol view
> API to the ledger layer

- shelley/chain-and-ledger/executable-spec/src/EpochBoundary.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
Still trying to figure out differences between staking snapshots, staking pool parameters, and staking itself. Lots of terms each time, should probably build ontology tree to keep track of all.
> Commented example 2C.

- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
I've added more tests/examples of what all the certificates in the shelley transactions look like when serialized. and also nonces.
> test all delegation cert serializations

- shelley/chain-and-ledger/cddl-spec/shelley.cddl
- shelley/chain-and-ledger/executable-spec/Makefile
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
More cbor serialization review and refinements. The cddl file even even parses with the ruby tool! :gem:
> transaction cbor cleanup

- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/MockTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
QC / HH generator for MIR certs
solves #1043
> MIR certificate generator

- shelley/chain-and-ledger/cddl-spec/shelley.cddl
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
- shelley/chain-and-ledger/executable-spec/src/Slot.hs
- shelley/chain-and-ledger/executable-spec/src/Updates.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
> cbor serialization of updates

- byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/src/Delegation/Certificates.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/test/Generator.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/MultiSigExamples.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
- shelley/chain-and-ledger/executable-spec/test/UnitTests.hs
> Generate Genesis Delegation certs

- shelley/chain-and-ledger/cddl-spec/shelley.cddl
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/OCert.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
We now have the full serialization of the block header bodies.
closes #1062 
closes #1063
> cbor encodings of block header bodies

- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestDeleg.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs
- checking that all entries are applied
- checking that the values are correctly applied, i.e., either added or overwritten if existing already
> Properties for generated MIR certificates

- shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs
I just updated my generators of Update to the latest PR.
Please let me know how to improve it.
Should close #1034
> QuickCheck generators for update proposals (protocol parameters and application versions and installer hashes)

- shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
This PR completes the CBOR serialization for blocks in shelley.
closes #1078
> shelley block CBOR serialization

- byron/semantics/executable-spec/src/Control/State/Transition/Trace/Generator/QuickCheck.hs
> [1103] Remove need for explicit sorting in Signal Shrinker

- shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Deleg.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Rupd.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Updn.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
We also add 'securityParameter', which is needed in the chain layer.
> Convert additional global parameters

- cabal.project
- nix/.stack.nix/cardano-binary.nix
- nix/.stack.nix/cardano-crypto-class.nix
- nix/.stack.nix/cardano-slotting.nix
- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Bbody.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
- stack.yaml
> hash merkel pair correctly #1127

- shelley/chain-and-ledger/executable-spec/test/Shrinkers.hs
activate transaction shrinking via output shrinking
> Activate shrinking of `TxOut`s of a `Tx`

- shelley/chain-and-ledger/executable-spec/test/ConcreteCryptoTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
Adds generators for script credentials for key registration / key de-registration and delegation
> Generate script credentials for certificates

- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/epoch.tex
- shelley/chain-and-ledger/formal-spec/properties.tex
This PR makes a few minor edits to the Shelley ledger spec that were uncovered during the Isabelle review. closes #1129
> small edits from isabelle review pt 2

- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
> Generate output base addresses with scripts / keys mixed

- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
adds new module `Generator.Core.Constants`
> Extract constants used in generators

- .buildkite/rebuild.hs
- byron/ledger/executable-spec/src/Ledger/Update.hs
- byron/ledger/formal-spec/blockchain-interface.tex
- byron/ledger/formal-spec/update-mechanism.tex
- nix/iohk-nix-src.json
Part of https://github.com/input-output-hk/cardano-ledger/pull/696
> Allow software versions to start from 0 or 1

- shelley/chain-and-ledger/executable-spec/delegation.cabal
- shelley/chain-and-ledger/executable-spec/test/ConcreteCryptoTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestLedger.hs
- shelley/chain-and-ledger/executable-spec/test/Shrinkers.hs
Closes #1065 
Closes #1064 
This PR introduces a basic CHAIN Trace generator which producing a chain of blocks. 
NOTE: the Blocks generated will not all be valid until we finalise the OVERLAY ticket #779
> [1065] Chain Trace Generator

- shelley/chain-and-ledger/executable-spec/src/PParams.hs
This seems to help with compile times.
> Change FromCBOR instance for PParams into applicative style

- nix/.stack.nix/cardano-binary.nix
- nix/.stack.nix/cardano-crypto-class.nix
- nix/.stack.nix/cardano-slotting.nix
- shelley/chain-and-ledger/executable-spec/src/Keys.hs
- stack.yaml
Include changes to KES typeclass interface which introduces explicit `updateKES`
function.
> Bump pointer to `cardano-crypto-class`

- shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
This PR adds reward withdrawals to the transaction generation.
75% of the time no withdrawals are generated.
20% of the time, between one and ten withdrawals are generated.
5% of the time, a random subset of all the reward accounts is selected.
closes #874
> generate reward withdrawals

- shelley/chain-and-ledger/executable-spec/src/BaseTypes.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Epoch.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ocert.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Utxow.hs
- shelley/chain-and-ledger/executable-spec/src/Updates.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestChain.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
> Add globals

- shelley/chain-and-ledger/executable-spec/src/Keys.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
add function to update KES key
add function to get current iteration count from KES key
add function to evolve key until specific iteration
> Extend KES functionality

- byron/cddl-spec/Makefile
- byron/cddl-spec/README.md
- byron/cddl-spec/binary.tex
- byron/cddl-spec/byron.cddl
- byron/cddl-spec/latexmkrc
- byron/cddl-spec/shell.nix
This repo needs to be the new reference location for it.
> Import the Byron CDDL from the cardano-sl repo

- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
The rewards account must have a zero balance in order to allow for credential
deregistration.
> Fix generator for `DeRegKey`

- shelley/chain-and-ledger/executable-spec/src/Tx.hs
- shelley/chain-and-ledger/executable-spec/src/TxData.hs
Change the `ScriptHash` type to be extendable to other (besides `MultiSig`) script languages in the future
> extend script addresses to different types of scripts

- shelley/chain-and-ledger/executable-spec/src/STS/Mir.hs
- shelley/chain-and-ledger/formal-spec/chain.tex
A few typos were noticed in #1191 after it was already merged. This small PR corrects them.
> correcting a few typos in the spec

- shelley/chain-and-ledger/executable-spec/test/Examples.hs
Inspired by #1200, I updated the main example to show more clearly that the stake distribution snapshots are rotated properly. In particular, after the first snapshot in example 2, a new actor delegates stake so that the second snapshot is different.
> update example 2 to have varying snapshots

- shelley/chain-and-ledger/executable-spec/src/Updates.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/ChainTrace.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/Constants.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Core/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/LedgerTrace/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Utxo/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/PropertyTests.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestChain.hs
- shelley/chain-and-ledger/executable-spec/test/Tests.hs
Closes #1212
(also closes #1114 although that has been manually closed already)
> [1114] [WIP ]Generate valid Updates and wire up to genTx

- shelley/chain-and-ledger/executable-spec/test/Examples.hs
It looks like #1221 broke the build. I do not know how it passed CI yesterday. :( This fixes it.
> fix examples

- shelley/chain-and-ledger/executable-spec/test/ConcreteCryptoTypes.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/ClassifyTraces.hs
- shelley/chain-and-ledger/executable-spec/test/Rules/TestChain.hs
Closes #1213
Closes #1214
should solve some of the problems we see when generating valid CHAIN traces
> [1214] Apply TICK to ledger state before passing to generator

- byron/ledger/executable-spec/cs-ledger.cabal
- byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXO.hs
- byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOW.hs
- byron/ledger/executable-spec/src/Cardano/Ledger/Spec/STS/UTXOWS.hs
- byron/ledger/executable-spec/src/Ledger/Core.hs
- byron/ledger/executable-spec/src/Ledger/Delegation.hs
- byron/ledger/executable-spec/src/Ledger/UTxO.hs
- byron/ledger/executable-spec/src/Ledger/Update.hs
- byron/semantics/executable-spec/small-steps.cabal
- byron/semantics/executable-spec/src/Control/State/Transition/Extended.hs
- byron/semantics/executable-spec/src/Control/State/Transition/Invalid/Trace.hs
- byron/semantics/executable-spec/src/Control/State/Transition/Trace.hs
> Add `NoUnexpectedThunks` for byron ledger spec

- shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs
The calculation is done as
σ × f
bₗ = ——————
n
where n is a random integer from [2,..,10].
This ensures that for the leader election we have
bₗ < 1 - (1 - f)^σ
> Use a calculated leader election value in generated blocks

- shelley/chain-and-ledger/executable-spec/src/STS/Prtcl.hs
We need it for the integration in Consensus.
> Derive Eq for PrtclState

- shelley/chain-and-ledger/executable-spec/src/STS/Avup.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Ppup.hs
> Transform STS multi-rules to a single rule

- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
Properly implement `bBodySize` and `bHeaderSize`.
closes #1153
> proper block header and body size functions

- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Delegation/QuickCheck.hs
Before, we generated non-zero pledges which was almost never met and led to zero rewards.
> Generate more non-zero rewards

- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/src/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/src/PParams.hs
- shelley/chain-and-ledger/executable-spec/src/STS/Overlay.hs
- shelley/chain-and-ledger/executable-spec/src/Updates.hs
- shelley/chain-and-ledger/executable-spec/test/Examples.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Update/QuickCheck.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Serialization.hs
Use partially pre-computed values for VRF checks.
> Active slot coefficient speed up for VRF checks

- shelley/chain-and-ledger/executable-spec/src/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/test/Generator/Block.hs
treat maximal iterations reached as failed VRF check
add some documentation
> Fix VRF check for max iterations, add documentation

- cabal.project
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Keys.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Utils.hs
- stack.yaml
This brings in https://github.com/input-output-hk/cardano-base/pull/84
> Update dependency on cardano-base

- shelley/design-spec/delegation_design_spec.tex
> Add the latest metadata design to the design doc.

- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Fees.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/UnitTests.hs
Adding the serialized bytes to the transaction size/fee examples for @SebastienGllmt
> adding bytes to fee examples

- byron/ledger/executable-spec/src/Ledger/Update.hs
This addresses an issue that  was introduced in #1311
> Fix trace generation wrt endorsement window.

- shelley/chain-and-ledger/formal-spec/address.tex
- shelley/chain-and-ledger/formal-spec/crypto-primitives.tex
- shelley/chain-and-ledger/formal-spec/default.nix
- shelley/chain-and-ledger/formal-spec/delegation.tex
- shelley/chain-and-ledger/formal-spec/frontmatter.tex
- shelley/chain-and-ledger/formal-spec/intro.tex
- shelley/chain-and-ledger/formal-spec/ledger-spec.tex
- shelley/chain-and-ledger/formal-spec/notation.tex
- shelley/chain-and-ledger/formal-spec/protocol-parameters.tex
- shelley/chain-and-ledger/formal-spec/transactions.tex
- shelley/chain-and-ledger/formal-spec/update.tex
corrections, with notes at
https://github.com/input-output-hk/cardano-ledger-specs/pull/1330
> corrections to formal spec

- shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/CDDL.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs
> [#1312] Make header a term instead of a group

- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs
Makes debugging testing easier!
> Add `HasCallStack` constraint in various places

- shelley/chain-and-ledger/formal-spec/chain.tex
- shelley/chain-and-ledger/formal-spec/delegation.tex
I didn't anticipate more reading when I opened the previous PR today, but I did read more after all and found some more typos.
> more minor typos

- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Core.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Delegation.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Update.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Generator/Utxo.hs
Helpful to debug various issues being seen in testing.
> Add 'HasCallStack' to other locations in the generators

- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Address.hs
The implementations will be replaced shortly. See #1367
> Add stubs for address serialisation and deserialisation

- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs
This will resolve https://github.com/input-output-hk/ouroboros-network/commit/5b2046957ac8e7a42a1bd040b5f6965c4b2b8984#diff-955d56d24d7bc708c6f53218212ecda7R323.
> Add NoUnexpectedThunks for PredicateFailure CHAIN

- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/MetaData.hs
This commit removes 34 lines of code and replaces them with 13 lines
(less verbose) and is easier to read because it limits itself to
more commonly used Haskell idioms.
> Remove only use of ViewPatterns

- shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Address.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/PropertyTests.hs
Please do not merge this until @dcoutts approves it.
> Fix deserialiseAddr

- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Serialization.hs
> More compact encoding of the overlay schedule

- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/NewEpoch.hs
This is useful for ouroboros-network testing, where we would like to
establish some stake at genesis.
> Expose function to calculate pool distribution.

- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BaseTypes.hs
Previously this was encoding each Word16 as its decimal form, and consequently the bytestring was longer than the 16 bytes it's supposed to be. Now we pack it directly into a bytestring.
Note that this was causing golden tests to fail, since the encoded form was too big and hence decoding was failing.
> Encode IPv6 addresses more compactly.

- .gitignore
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs
Adds an exposed function to the Wallet API to get the UTxO filtered by address.
> Filter UTxO by address

- shelley/chain-and-ledger/executable-spec/shelley-spec-ledger.cabal
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/Examples/Fees.hs
- shelley/chain-and-ledger/formal-spec/ledger-spec.tex
- shelley/chain-and-ledger/formal-spec/txsize.tex
This PR replaces the `txsize` function with something simpler and less error prone.
> simplified txsize calculation

- goguen/formal-spec/Formal Spec with Plutus Integration - Review 3.rtf
- goguen/formal-spec/Formal Spec with Plutus Integration - Review 4.rtf
- goguen/formal-spec/frontmatter.tex
- goguen/formal-spec/protocol-parameters.tex
- goguen/formal-spec/transactions.tex
- goguen/formal-spec/utxo.tex
reviews 3 and 4 from internal auditor Yun Lu addressed
> review 3 and 4 from internal auditor

- nix/sources.json
- scripts/ormolise.sh
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxow.hs
- shelley/chain-and-ledger/executable-spec/test/Test/Cardano/Crypto/VRF/Fake.hs
Ormolu now works on `Prtcl.hs`, so run it.
Also switch to checking idempotence.
> Update ormolu: now works on Prtcl.hs

- shelley-mc/formal-spec/transactions.tex
- shelley-mc/formal-spec/utxo.tex
Just some random improvements I found
> minor improvements and fixes to the mc-spec

- .buildkite/pipeline.yml
- scripts/ormolise.sh
- shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs
> Various buildkite improvements
